
package it.csi.smranag.smrgaa.ws.sianfa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.9
 * 2020-01-14T15:41:55.465+01:00
 * Generated source version: 2.4.9
 */

@WebFault(name = "Exception", targetNamespace = "http://service.sianfa.agricoltura.aizoon.it/")
public class Exception_Exception extends java.lang.Exception {
    
    private it.csi.smranag.smrgaa.ws.sianfa.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, it.csi.smranag.smrgaa.ws.sianfa.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, it.csi.smranag.smrgaa.ws.sianfa.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public it.csi.smranag.smrgaa.ws.sianfa.Exception getFaultInfo() {
        return this.exception;
    }
}
