
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.csi.smranag.smrgaa.ws.sianfa;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.9
 * 2020-01-14T15:41:55.478+01:00
 * Generated source version: 2.4.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "ServiceSianfaImplService",
                      portName = "ServiceSianfaImplPort",
                      targetNamespace = "http://service.sianfa.agricoltura.aizoon.it/",
                      wsdlLocation = "file:/C:/Users/ALESSA~1.SOR/AppData/Local/Temp/tempdir977213889877074501.tmp/ServiceSianfaImpl_1.wsdl",
                      endpointInterface = "it.csi.smranag.smrgaa.ws.sianfa.ServiceSianfa")
                      
public class ServiceSianfaImpl implements ServiceSianfa {

    private static final Logger LOG = Logger.getLogger(ServiceSianfaImpl.class.getName());

    /* (non-Javadoc)
     * @see it.csi.smranag.smrgaa.ws.sianfa.ServiceSianfa#isAlive(*
     */
    public boolean isAlive() throws Exception_Exception    { 
        LOG.info("Executing operation isAlive");
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see it.csi.smranag.smrgaa.ws.sianfa.ServiceSianfa#testResources(*
     */
    public boolean testResources() throws Exception_Exception    { 
        LOG.info("Executing operation testResources");
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see it.csi.smranag.smrgaa.ws.sianfa.ServiceSianfa#aggiornaFascicoloAziendale(java.lang.String  arg0 ,)java.lang.Long  arg1 )*
     */
    public boolean aggiornaFascicoloAziendale(java.lang.String arg0,java.lang.Long arg1) throws Exception_Exception    { 
        LOG.info("Executing operation aggiornaFascicoloAziendale");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see it.csi.smranag.smrgaa.ws.sianfa.ServiceSianfa#getAggiornamentiFascicolo(java.lang.String  arg0 )*
     */
    public it.csi.smranag.smrgaa.ws.sianfa.SianEsito getAggiornamentiFascicolo(java.lang.String arg0) throws Exception_Exception    { 
        LOG.info("Executing operation getAggiornamentiFascicolo");
        System.out.println(arg0);
        try {
            it.csi.smranag.smrgaa.ws.sianfa.SianEsito _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

}
