package it.csi.smranag.smrgaa.ws.sianfa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.9
 * 2020-01-14T15:41:55.498+01:00
 * Generated source version: 2.4.9
 * 
 */
@WebServiceClient(name = "ServiceSianfaImplService", 
                  wsdlLocation = "file:/C:/Users/ALESSA~1.SOR/AppData/Local/Temp/tempdir977213889877074501.tmp/ServiceSianfaImpl_1.wsdl",
                  targetNamespace = "http://service.sianfa.agricoltura.aizoon.it/") 
public class ServiceSianfaImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.sianfa.agricoltura.aizoon.it/", "ServiceSianfaImplService");
    public final static QName ServiceSianfaImplPort = new QName("http://service.sianfa.agricoltura.aizoon.it/", "ServiceSianfaImplPort");
    static {                
    	URL url = ServiceSianfaImplService.class.getResource("/fascicoloAll.wsdl");        
        WSDL_LOCATION = url;
    }

    public ServiceSianfaImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceSianfaImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceSianfaImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceSianfaImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceSianfaImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceSianfaImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ServiceSianfa
     */
    @WebEndpoint(name = "ServiceSianfaImplPort")
    public ServiceSianfa getServiceSianfaImplPort() {
        return super.getPort(ServiceSianfaImplPort, ServiceSianfa.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceSianfa
     */
    @WebEndpoint(name = "ServiceSianfaImplPort")
    public ServiceSianfa getServiceSianfaImplPort(WebServiceFeature... features) {
        return super.getPort(ServiceSianfaImplPort, ServiceSianfa.class, features);
    }

}
