
package it.csi.smranag.smrgaa.ws.sianfa;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.9
 * 2020-01-14T15:41:55.387+01:00
 * Generated source version: 2.4.9
 * 
 */
public final class ServiceSianfa_ServiceSianfaImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.sianfa.agricoltura.aizoon.it/", "ServiceSianfaImplService");

    private ServiceSianfa_ServiceSianfaImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServiceSianfaImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ServiceSianfaImplService ss = new ServiceSianfaImplService(wsdlURL, SERVICE_NAME);
        ServiceSianfa port = ss.getServiceSianfaImplPort();  
        
        {
        System.out.println("Invoking isAlive...");
        try {
            boolean _isAlive__return = port.isAlive();
            System.out.println("isAlive.result=" + _isAlive__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking testResources...");
        try {
            boolean _testResources__return = port.testResources();
            System.out.println("testResources.result=" + _testResources__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking aggiornaFascicoloAziendale...");
        java.lang.String _aggiornaFascicoloAziendale_arg0 = "";
        java.lang.Long _aggiornaFascicoloAziendale_arg1 = null;
        try {
            boolean _aggiornaFascicoloAziendale__return = port.aggiornaFascicoloAziendale(_aggiornaFascicoloAziendale_arg0, _aggiornaFascicoloAziendale_arg1);
            System.out.println("aggiornaFascicoloAziendale.result=" + _aggiornaFascicoloAziendale__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAggiornamentiFascicolo...");
        java.lang.String _getAggiornamentiFascicolo_arg0 = "";
        try {
            it.csi.smranag.smrgaa.ws.sianfa.SianEsito _getAggiornamentiFascicolo__return = port.getAggiornamentiFascicolo(_getAggiornamentiFascicolo_arg0);
            System.out.println("getAggiornamentiFascicolo.result=" + _getAggiornamentiFascicolo__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
