
package it.csi.smranag.smrgaa.ws.sianfa;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.4.9
 * 2020-01-14T15:41:55.496+01:00
 * Generated source version: 2.4.9
 * 
 */
 
public class ServiceSianfa_ServiceSianfaImplPort_Server{

    protected ServiceSianfa_ServiceSianfaImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ServiceSianfaImpl();
        String address = "http://localhost:8330/sianfa/ServiceSianfaImpl";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ServiceSianfa_ServiceSianfaImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
