
package it.csi.smranag.smrgaa.ws.gaaserv.marcatemporale;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-10-20T16:33:40.963+02:00
 * Generated source version: 3.1.8
 */

@WebFault(name = "Exception", targetNamespace = "http://service.gaaserv.agricoltura.aizoon.it/")
public class Exception_Exception extends java.lang.Exception {
    
    private it.csi.smranag.smrgaa.ws.gaaserv.marcatemporale.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, it.csi.smranag.smrgaa.ws.gaaserv.marcatemporale.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, it.csi.smranag.smrgaa.ws.gaaserv.marcatemporale.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public it.csi.smranag.smrgaa.ws.gaaserv.marcatemporale.Exception getFaultInfo() {
        return this.exception;
    }
}
