package it.csi.smranag.smrgaa.ws.gaaserv.marcatemporale;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-10-20T16:33:41.011+02:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://service.gaaserv.agricoltura.aizoon.it/", name = "ServiceMarcaTemporaleserv")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceMarcaTemporaleserv {

    @WebMethod
    @RequestWrapper(localName = "getMarcaTemporale", targetNamespace = "http://service.gaaserv.agricoltura.aizoon.it/", className = "it.csi.smranag.smrgaa.ws.gaaserv.marcatemporale.GetMarcaTemporale")
    @ResponseWrapper(localName = "getMarcaTemporaleResponse", targetNamespace = "http://service.gaaserv.agricoltura.aizoon.it/", className = "it.csi.smranag.smrgaa.ws.gaaserv.marcatemporale.GetMarcaTemporaleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public byte[] getMarcaTemporale(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "isAlive", targetNamespace = "http://service.gaaserv.agricoltura.aizoon.it/", className = "it.csi.smranag.smrgaa.ws.gaaserv.marcatemporale.IsAlive")
    @ResponseWrapper(localName = "isAliveResponse", targetNamespace = "http://service.gaaserv.agricoltura.aizoon.it/", className = "it.csi.smranag.smrgaa.ws.gaaserv.marcatemporale.IsAliveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean isAlive() throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "testResources", targetNamespace = "http://service.gaaserv.agricoltura.aizoon.it/", className = "it.csi.smranag.smrgaa.ws.gaaserv.marcatemporale.TestResources")
    @ResponseWrapper(localName = "testResourcesResponse", targetNamespace = "http://service.gaaserv.agricoltura.aizoon.it/", className = "it.csi.smranag.smrgaa.ws.gaaserv.marcatemporale.TestResourcesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean testResources() throws Exception_Exception;
}
