/* Generated by Together */
package it.csi.solmr.util;

import java.text.*;

/**
 *
 * <p>Title: ADVI: Acquisizione Domande Via Internet</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2002</p>
 * <p>Company: CSI Piemonte</p>
 * @author Luigi R. Viggiano
 * @version $Revision: 1.1 $
 */
public class ValidationError implements ValueObject {

    /**
	 *
	 */
	private static final long serialVersionUID = -2462172976633545945L;

	/**
     * Il messaggio dell'errore.
     */
    String message;

    /**
     * I parametri del messaggio. Vengono sostituiti nella stringa.
     */
    Object[] values;

    public ValidationError(String message)
    {
      if (message!=null)
      {
        this.message = message.replace('\n', ' ');
      }
    }

    public ValidationError(String message, Object value1){
      if (message!=null)
      {
        this.message = message.replace('\n', ' ');
      }
      values = new Object[] {value1};
    }

    public ValidationError(String message, Object value1, Object value2){
      if (message!=null)
      {
        this.message = message.replace('\n', ' ');
      }
      values = new Object[] {value1, value2};
    }

    public ValidationError(String message, Object value1, Object value2, Object value3){
      if (message!=null)
      {
        this.message = message.replace('\n', ' ');
      }
      values = new Object[] {value1, value2, value3};
    }

    public ValidationError(String message, Object value1, Object value2, Object value3, Object value4){
      if (message!=null)
      {
        this.message = message.replace('\n', ' ');
      }
      values = new Object[] {value1, value2, value3, value4};
    }

    public String getMessage() {
        return MessageFormat.format(String.valueOf(message), values);
    }

    public Object[] getValues(){
        return values;
    }
}
