
package it.csi.smranag.smrgaa.ws.papuaserv.messaggistica;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.9
 * 2016-07-15T23:56:15.100+02:00
 * Generated source version: 2.4.9
 */

@WebFault(name = "InternalException", targetNamespace = "http://papuaserv.webservice.business.papuaserv.papua.csi.it/")
public class InternalException_Exception extends Exception {
    
    private it.csi.smranag.smrgaa.ws.papuaserv.messaggistica.InternalException internalException;

    public InternalException_Exception() {
        super();
    }
    
    public InternalException_Exception(String message) {
        super(message);
    }
    
    public InternalException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InternalException_Exception(String message, it.csi.smranag.smrgaa.ws.papuaserv.messaggistica.InternalException internalException) {
        super(message);
        this.internalException = internalException;
    }

    public InternalException_Exception(String message, it.csi.smranag.smrgaa.ws.papuaserv.messaggistica.InternalException internalException, Throwable cause) {
        super(message, cause);
        this.internalException = internalException;
    }

    public it.csi.smranag.smrgaa.ws.papuaserv.messaggistica.InternalException getFaultInfo() {
        return this.internalException;
    }
}
