
package it.csi.smranag.smrgaa.ws.papuaserv.messaggistica;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.9
 * 2016-07-15T23:56:15.082+02:00
 * Generated source version: 2.4.9
 */

@WebFault(name = "LogoutException", targetNamespace = "http://papuaserv.webservice.business.papuaserv.papua.csi.it/")
public class LogoutException_Exception extends Exception {
    
    private it.csi.smranag.smrgaa.ws.papuaserv.messaggistica.LogoutException logoutException;

    public LogoutException_Exception() {
        super();
    }
    
    public LogoutException_Exception(String message) {
        super(message);
    }
    
    public LogoutException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public LogoutException_Exception(String message, it.csi.smranag.smrgaa.ws.papuaserv.messaggistica.LogoutException logoutException) {
        super(message);
        this.logoutException = logoutException;
    }

    public LogoutException_Exception(String message, it.csi.smranag.smrgaa.ws.papuaserv.messaggistica.LogoutException logoutException, Throwable cause) {
        super(message, cause);
        this.logoutException = logoutException;
    }

    public it.csi.smranag.smrgaa.ws.papuaserv.messaggistica.LogoutException getFaultInfo() {
        return this.logoutException;
    }
}
