package it.csi.smranag.smrgaa.ws.papuaserv.messaggistica;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.9
 * 2016-07-15T23:56:15.118+02:00
 * Generated source version: 2.4.9
 * 
 */
@WebServiceClient(name = "messaggistica", 
                  wsdlLocation = "file:/C:/Users/PD9D3~1.CHI/AppData/Local/Temp/tempdir4160363240087648.tmp/messaggistica_1.wsdl",
                  targetNamespace = "http://papuaserv.webservice.business.papuaserv.papua.csi.it/") 
public class Messaggistica extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://papuaserv.webservice.business.papuaserv.papua.csi.it/", "messaggistica");
    public final static QName MessaggisticaPort = new QName("http://papuaserv.webservice.business.papuaserv.papua.csi.it/", "messaggisticaPort");
    static {
    	URL url = Messaggistica.class.getResource("/papuaserv_ws_messaggistica.wsdl");
        WSDL_LOCATION = url;
    }

    public Messaggistica(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Messaggistica(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Messaggistica() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Messaggistica(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Messaggistica(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Messaggistica(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IMessaggisticaWS
     */
    @WebEndpoint(name = "messaggisticaPort")
    public IMessaggisticaWS getMessaggisticaPort() {
        return super.getPort(MessaggisticaPort, IMessaggisticaWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMessaggisticaWS
     */
    @WebEndpoint(name = "messaggisticaPort")
    public IMessaggisticaWS getMessaggisticaPort(WebServiceFeature... features) {
        return super.getPort(MessaggisticaPort, IMessaggisticaWS.class, features);
    }

}
