package it.csi.solmr.ws.infoc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.9
 * 2017-07-25T09:26:37.369+02:00
 * Generated source version: 2.4.9
 * 
 */
@WebService(targetNamespace = "http://servizio.frontend.ls.com", name = "LSICServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface LSICServicePortType {

    @WebMethod(action = "urn:cercaPerCodiceFiscale")
    @Action(input = "urn:cercaPerCodiceFiscale", output = "urn:cercaPerCodiceFiscaleResponse")
    @RequestWrapper(localName = "cercaPerCodiceFiscale", targetNamespace = "http://servizio.frontend.ls.com", className = "it.csi.solmr.ws.infoc.CercaPerCodiceFiscale")
    @ResponseWrapper(localName = "cercaPerCodiceFiscaleResponse", targetNamespace = "http://servizio.frontend.ls.com", className = "it.csi.solmr.ws.infoc.CercaPerCodiceFiscaleResponse")
    @WebResult(name = "return", targetNamespace = "http://servizio.frontend.ls.com")
    public it.csi.solmr.ws.infoc.Azienda cercaPerCodiceFiscale(
        @WebParam(name = "codiceFiscale", targetNamespace = "http://servizio.frontend.ls.com")
        java.lang.String codiceFiscale,
        @WebParam(name = "codFonte", targetNamespace = "http://servizio.frontend.ls.com")
        java.lang.String codFonte
    );

    @WebMethod(action = "urn:cercaPuntualeSede")
    @Action(input = "urn:cercaPuntualeSede", output = "urn:cercaPuntualeSedeResponse")
    @RequestWrapper(localName = "cercaPuntualeSede", targetNamespace = "http://servizio.frontend.ls.com", className = "it.csi.solmr.ws.infoc.CercaPuntualeSede")
    @ResponseWrapper(localName = "cercaPuntualeSedeResponse", targetNamespace = "http://servizio.frontend.ls.com", className = "it.csi.solmr.ws.infoc.CercaPuntualeSedeResponse")
    @WebResult(name = "return", targetNamespace = "http://servizio.frontend.ls.com")
    public it.csi.solmr.ws.infoc.Sede cercaPuntualeSede(
        @WebParam(name = "codiceFiscale", targetNamespace = "http://servizio.frontend.ls.com")
        java.lang.String codiceFiscale,
        @WebParam(name = "progrSede", targetNamespace = "http://servizio.frontend.ls.com")
        java.lang.String progrSede,
        @WebParam(name = "codFonte", targetNamespace = "http://servizio.frontend.ls.com")
        java.lang.String codFonte
    );

    @WebMethod(action = "urn:cercaPerFiltriCodFiscFonte")
    @Action(input = "urn:cercaPerFiltriCodFiscFonte", output = "urn:cercaPerFiltriCodFiscFonteResponse")
    @RequestWrapper(localName = "cercaPerFiltriCodFiscFonte", targetNamespace = "http://servizio.frontend.ls.com", className = "it.csi.solmr.ws.infoc.CercaPerFiltriCodFiscFonte")
    @ResponseWrapper(localName = "cercaPerFiltriCodFiscFonteResponse", targetNamespace = "http://servizio.frontend.ls.com", className = "it.csi.solmr.ws.infoc.CercaPerFiltriCodFiscFonteResponse")
    @WebResult(name = "return", targetNamespace = "http://servizio.frontend.ls.com")
    public java.util.List<it.csi.solmr.ws.infoc.ListaPersonaCaricaInfoc> cercaPerFiltriCodFiscFonte(
        @WebParam(name = "codiceFiscale", targetNamespace = "http://servizio.frontend.ls.com")
        java.lang.String codiceFiscale,
        @WebParam(name = "codFonte", targetNamespace = "http://servizio.frontend.ls.com")
        java.lang.String codFonte
    );

    @WebMethod(action = "urn:cercaPuntualePersonaRI")
    @Action(input = "urn:cercaPuntualePersonaRI", output = "urn:cercaPuntualePersonaRIResponse")
    @RequestWrapper(localName = "cercaPuntualePersonaRI", targetNamespace = "http://servizio.frontend.ls.com", className = "it.csi.solmr.ws.infoc.CercaPuntualePersonaRI")
    @ResponseWrapper(localName = "cercaPuntualePersonaRIResponse", targetNamespace = "http://servizio.frontend.ls.com", className = "it.csi.solmr.ws.infoc.CercaPuntualePersonaRIResponse")
    @WebResult(name = "return", targetNamespace = "http://servizio.frontend.ls.com")
    public it.csi.solmr.ws.infoc.PersonaRIInfoc cercaPuntualePersonaRI(
        @WebParam(name = "codiceFiscale", targetNamespace = "http://servizio.frontend.ls.com")
        java.lang.String codiceFiscale,
        @WebParam(name = "progrPersona", targetNamespace = "http://servizio.frontend.ls.com")
        java.lang.String progrPersona,
        @WebParam(name = "codFonte", targetNamespace = "http://servizio.frontend.ls.com")
        java.lang.String codFonte
    );
}
