//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Visibility"/>
 *         &lt;element ref="{}HeadAllegati"/>
 *         &lt;element ref="{}AllegatiNormali"/>
 *         &lt;element ref="{}HeadCondizionalita"/>
 *         &lt;element ref="{}AllegatiCondizionalita"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "visibility",
    "headAllegati",
    "allegatiNormali",
    "headCondizionalita",
    "allegatiCondizionalita"
})
@XmlRootElement(name = "Allegati")
public class Allegati {

    @XmlElement(name = "Visibility")
    protected boolean visibility;
    @XmlElement(name = "HeadAllegati")
    protected boolean headAllegati;
    @XmlElement(name = "AllegatiNormali", required = true)
    protected AllegatiNormali allegatiNormali;
    @XmlElement(name = "HeadCondizionalita")
    protected boolean headCondizionalita;
    @XmlElement(name = "AllegatiCondizionalita", required = true)
    protected AllegatiCondizionalita allegatiCondizionalita;

    /**
     * Gets the value of the visibility property.
     * 
     */
    public boolean isVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     */
    public void setVisibility(boolean value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the headAllegati property.
     * 
     */
    public boolean isHeadAllegati() {
        return headAllegati;
    }

    /**
     * Sets the value of the headAllegati property.
     * 
     */
    public void setHeadAllegati(boolean value) {
        this.headAllegati = value;
    }

    /**
     * Gets the value of the allegatiNormali property.
     * 
     * @return
     *     possible object is
     *     {@link AllegatiNormali }
     *     
     */
    public AllegatiNormali getAllegatiNormali() {
        return allegatiNormali;
    }

    /**
     * Sets the value of the allegatiNormali property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllegatiNormali }
     *     
     */
    public void setAllegatiNormali(AllegatiNormali value) {
        this.allegatiNormali = value;
    }

    /**
     * Gets the value of the headCondizionalita property.
     * 
     */
    public boolean isHeadCondizionalita() {
        return headCondizionalita;
    }

    /**
     * Sets the value of the headCondizionalita property.
     * 
     */
    public void setHeadCondizionalita(boolean value) {
        this.headCondizionalita = value;
    }

    /**
     * Gets the value of the allegatiCondizionalita property.
     * 
     * @return
     *     possible object is
     *     {@link AllegatiCondizionalita }
     *     
     */
    public AllegatiCondizionalita getAllegatiCondizionalita() {
        return allegatiCondizionalita;
    }

    /**
     * Sets the value of the allegatiCondizionalita property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllegatiCondizionalita }
     *     
     */
    public void setAllegatiCondizionalita(AllegatiCondizionalita value) {
        this.allegatiCondizionalita = value;
    }

}
