//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Iban"/>
 *         &lt;element ref="{}Istituto"/>
 *         &lt;element ref="{}Agenzia"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "iban",
    "istituto",
    "agenzia"
})
@XmlRootElement(name = "Conto")
public class Conto {

    @XmlElement(name = "Iban", required = true)
    protected String iban;
    @XmlElement(name = "Istituto", required = true)
    protected String istituto;
    @XmlElement(name = "Agenzia", required = true)
    protected String agenzia;

    /**
     * Gets the value of the iban property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIban() {
        return iban;
    }

    /**
     * Sets the value of the iban property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIban(String value) {
        this.iban = value;
    }

    /**
     * Gets the value of the istituto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIstituto() {
        return istituto;
    }

    /**
     * Sets the value of the istituto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIstituto(String value) {
        this.istituto = value;
    }

    /**
     * Gets the value of the agenzia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgenzia() {
        return agenzia;
    }

    /**
     * Sets the value of the agenzia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgenzia(String value) {
        this.agenzia = value;
    }

}
