//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}valoreDich"/>
 *         &lt;element ref="{}valoreCheck"/>
 *         &lt;element ref="{}tipoRiga"/>
 *         &lt;element ref="{}colonneRiga"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "valoreDich",
    "valoreCheck",
    "tipoRiga",
    "colonneRiga"
})
@XmlRootElement(name = "dichiarazioneCheck")
public class DichiarazioneCheck {

    @XmlElement(required = true)
    protected String valoreDich;
    @XmlElement(required = true)
    protected BigInteger valoreCheck;
    @XmlElement(required = true)
    protected String tipoRiga;
    @XmlElement(required = true)
    protected BigInteger colonneRiga;

    /**
     * Gets the value of the valoreDich property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValoreDich() {
        return valoreDich;
    }

    /**
     * Sets the value of the valoreDich property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValoreDich(String value) {
        this.valoreDich = value;
    }

    /**
     * Gets the value of the valoreCheck property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getValoreCheck() {
        return valoreCheck;
    }

    /**
     * Sets the value of the valoreCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setValoreCheck(BigInteger value) {
        this.valoreCheck = value;
    }

    /**
     * Gets the value of the tipoRiga property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoRiga() {
        return tipoRiga;
    }

    /**
     * Sets the value of the tipoRiga property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoRiga(String value) {
        this.tipoRiga = value;
    }

    /**
     * Gets the value of the colonneRiga property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getColonneRiga() {
        return colonneRiga;
    }

    /**
     * Sets the value of the colonneRiga property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setColonneRiga(BigInteger value) {
        this.colonneRiga = value;
    }

}
