//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Tipo"/>
 *         &lt;element ref="{}AnnoRiatt"/>
 *         &lt;element ref="{}UnitaMisuraDimensione"/>
 *         &lt;element ref="{}Dimensione"/>
 *         &lt;element ref="{}Sup"/>
 *         &lt;element ref="{}Particelle"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tipo",
    "annoRiatt",
    "unitaMisuraDimensione",
    "dimensione",
    "sup",
    "particelle"
})
@XmlRootElement(name = "Fabbricato")
public class Fabbricato {

    @XmlElement(name = "Tipo", required = true)
    protected String tipo;
    @XmlElement(name = "AnnoRiatt", required = true)
    protected String annoRiatt;
    @XmlElement(name = "UnitaMisuraDimensione", required = true)
    protected String unitaMisuraDimensione;
    @XmlElement(name = "Dimensione", required = true)
    protected String dimensione;
    @XmlElement(name = "Sup", required = true)
    protected String sup;
    @XmlElement(name = "Particelle", required = true)
    protected Particelle particelle;

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipo(String value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the annoRiatt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnoRiatt() {
        return annoRiatt;
    }

    /**
     * Sets the value of the annoRiatt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnoRiatt(String value) {
        this.annoRiatt = value;
    }

    /**
     * Gets the value of the unitaMisuraDimensione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitaMisuraDimensione() {
        return unitaMisuraDimensione;
    }

    /**
     * Sets the value of the unitaMisuraDimensione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitaMisuraDimensione(String value) {
        this.unitaMisuraDimensione = value;
    }

    /**
     * Gets the value of the dimensione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDimensione() {
        return dimensione;
    }

    /**
     * Sets the value of the dimensione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDimensione(String value) {
        this.dimensione = value;
    }

    /**
     * Gets the value of the sup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSup() {
        return sup;
    }

    /**
     * Sets the value of the sup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSup(String value) {
        this.sup = value;
    }

    /**
     * Gets the value of the particelle property.
     * 
     * @return
     *     possible object is
     *     {@link Particelle }
     *     
     */
    public Particelle getParticelle() {
        return particelle;
    }

    /**
     * Sets the value of the particelle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Particelle }
     *     
     */
    public void setParticelle(Particelle value) {
        this.particelle = value;
    }

}
