//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Visibility"/>
 *         &lt;element ref="{}LuogoFirma"/>
 *         &lt;element ref="{}DataFirma"/>
 *         &lt;element ref="{}LuogoEData"/>
 *         &lt;element ref="{}EtichettaFirma"/>
 *         &lt;element ref="{}Firmatario"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "visibility",
    "luogoFirma",
    "dataFirma",
    "luogoEData",
    "etichettaFirma",
    "firmatario"
})
@XmlRootElement(name = "Firma2")
public class Firma2 {

    @XmlElement(name = "Visibility")
    protected boolean visibility;
    @XmlElement(name = "LuogoFirma", required = true)
    protected String luogoFirma;
    @XmlElement(name = "DataFirma", required = true)
    protected String dataFirma;
    @XmlElement(name = "LuogoEData", required = true)
    protected String luogoEData;
    @XmlElement(name = "EtichettaFirma", required = true)
    protected String etichettaFirma;
    @XmlElement(name = "Firmatario", required = true)
    protected String firmatario;

    /**
     * Gets the value of the visibility property.
     * 
     */
    public boolean isVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     */
    public void setVisibility(boolean value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the luogoFirma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLuogoFirma() {
        return luogoFirma;
    }

    /**
     * Sets the value of the luogoFirma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLuogoFirma(String value) {
        this.luogoFirma = value;
    }

    /**
     * Gets the value of the dataFirma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataFirma() {
        return dataFirma;
    }

    /**
     * Sets the value of the dataFirma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataFirma(String value) {
        this.dataFirma = value;
    }

    /**
     * Gets the value of the luogoEData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLuogoEData() {
        return luogoEData;
    }

    /**
     * Sets the value of the luogoEData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLuogoEData(String value) {
        this.luogoEData = value;
    }

    /**
     * Gets the value of the etichettaFirma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEtichettaFirma() {
        return etichettaFirma;
    }

    /**
     * Sets the value of the etichettaFirma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEtichettaFirma(String value) {
        this.etichettaFirma = value;
    }

    /**
     * Gets the value of the firmatario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirmatario() {
        return firmatario;
    }

    /**
     * Sets the value of the firmatario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirmatario(String value) {
        this.firmatario = value;
    }

}
