//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Visibility"/>
 *         &lt;element ref="{}Titolo1"/>
 *         &lt;element ref="{}Titolo2"/>
 *         &lt;element ref="{}Castelletto"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "visibility",
    "titolo1",
    "titolo2",
    "castelletto"
})
@XmlRootElement(name = "HeaderLandscape")
public class HeaderLandscape {

    @XmlElement(name = "Visibility")
    protected boolean visibility;
    @XmlElement(name = "Titolo1", required = true)
    protected String titolo1;
    @XmlElement(name = "Titolo2", required = true)
    protected String titolo2;
    @XmlElement(name = "Castelletto", required = true)
    protected Castelletto castelletto;

    /**
     * Gets the value of the visibility property.
     * 
     */
    public boolean isVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     */
    public void setVisibility(boolean value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the titolo1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitolo1() {
        return titolo1;
    }

    /**
     * Sets the value of the titolo1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitolo1(String value) {
        this.titolo1 = value;
    }

    /**
     * Gets the value of the titolo2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitolo2() {
        return titolo2;
    }

    /**
     * Sets the value of the titolo2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitolo2(String value) {
        this.titolo2 = value;
    }

    /**
     * Gets the value of the castelletto property.
     * 
     * @return
     *     possible object is
     *     {@link Castelletto }
     *     
     */
    public Castelletto getCastelletto() {
        return castelletto;
    }

    /**
     * Sets the value of the castelletto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Castelletto }
     *     
     */
    public void setCastelletto(Castelletto value) {
        this.castelletto = value;
    }

}
