//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Visibility"/>
 *         &lt;element ref="{}Oggetto"/>
 *         &lt;element ref="{}Titolone"/>
 *         &lt;element ref="{}Sottotitolo"/>
 *         &lt;element ref="{}Sottoscritto"/>
 *         &lt;element ref="{}InQualita"/>
 *         &lt;element ref="{}Azienda"/>
 *         &lt;element ref="{}MotivoRichiesta"/>
 *         &lt;element ref="{}Note"/>
 *         &lt;element ref="{}Firma2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "visibility",
    "oggetto",
    "titolone",
    "sottotitolo",
    "sottoscritto",
    "inQualita",
    "azienda",
    "motivoRichiesta",
    "note",
    "firma2"
})
@XmlRootElement(name = "IntroRichVar")
public class IntroRichVar {

    @XmlElement(name = "Visibility")
    protected boolean visibility;
    @XmlElement(name = "Oggetto", required = true)
    protected String oggetto;
    @XmlElement(name = "Titolone", required = true)
    protected String titolone;
    @XmlElement(name = "Sottotitolo", required = true)
    protected String sottotitolo;
    @XmlElement(name = "Sottoscritto", required = true)
    protected String sottoscritto;
    @XmlElement(name = "InQualita", required = true)
    protected String inQualita;
    @XmlElement(name = "Azienda", required = true)
    protected String azienda;
    @XmlElement(name = "MotivoRichiesta", required = true)
    protected String motivoRichiesta;
    @XmlElement(name = "Note", required = true)
    protected String note;
    @XmlElement(name = "Firma2", required = true)
    protected Firma2 firma2;

    /**
     * Gets the value of the visibility property.
     * 
     */
    public boolean isVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     */
    public void setVisibility(boolean value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the oggetto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOggetto() {
        return oggetto;
    }

    /**
     * Sets the value of the oggetto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOggetto(String value) {
        this.oggetto = value;
    }

    /**
     * Gets the value of the titolone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitolone() {
        return titolone;
    }

    /**
     * Sets the value of the titolone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitolone(String value) {
        this.titolone = value;
    }

    /**
     * Gets the value of the sottotitolo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSottotitolo() {
        return sottotitolo;
    }

    /**
     * Sets the value of the sottotitolo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSottotitolo(String value) {
        this.sottotitolo = value;
    }

    /**
     * Gets the value of the sottoscritto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSottoscritto() {
        return sottoscritto;
    }

    /**
     * Sets the value of the sottoscritto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSottoscritto(String value) {
        this.sottoscritto = value;
    }

    /**
     * Gets the value of the inQualita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInQualita() {
        return inQualita;
    }

    /**
     * Sets the value of the inQualita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInQualita(String value) {
        this.inQualita = value;
    }

    /**
     * Gets the value of the azienda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAzienda() {
        return azienda;
    }

    /**
     * Sets the value of the azienda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAzienda(String value) {
        this.azienda = value;
    }

    /**
     * Gets the value of the motivoRichiesta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotivoRichiesta() {
        return motivoRichiesta;
    }

    /**
     * Sets the value of the motivoRichiesta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotivoRichiesta(String value) {
        this.motivoRichiesta = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the firma2 property.
     * 
     * @return
     *     possible object is
     *     {@link Firma2 }
     *     
     */
    public Firma2 getFirma2() {
        return firma2;
    }

    /**
     * Sets the value of the firma2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Firma2 }
     *     
     */
    public void setFirma2(Firma2 value) {
        this.firma2 = value;
    }

}
