//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Genere"/>
 *         &lt;element ref="{}Categoria"/>
 *         &lt;element ref="{}Anno"/>
 *         &lt;element ref="{}Marca"/>
 *         &lt;element ref="{}Tipo"/>
 *         &lt;element ref="{}FormaPossesso"/>
 *         &lt;element ref="{}PercPossessoMacch"/>
 *         &lt;element ref="{}Telaio"/>
 *         &lt;element ref="{}DataCarico"/>
 *         &lt;element ref="{}DataScarico"/>
 *         &lt;element ref="{}Variazione"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "genere",
    "categoria",
    "anno",
    "marca",
    "tipo",
    "formaPossesso",
    "percPossessoMacch",
    "telaio",
    "dataCarico",
    "dataScarico",
    "variazione"
})
@XmlRootElement(name = "MacchinaVar")
public class MacchinaVar {

    @XmlElement(name = "Genere", required = true)
    protected String genere;
    @XmlElement(name = "Categoria", required = true)
    protected String categoria;
    @XmlElement(name = "Anno", required = true)
    protected String anno;
    @XmlElement(name = "Marca", required = true)
    protected String marca;
    @XmlElement(name = "Tipo", required = true)
    protected String tipo;
    @XmlElement(name = "FormaPossesso", required = true)
    protected String formaPossesso;
    @XmlElement(name = "PercPossessoMacch", required = true)
    protected String percPossessoMacch;
    @XmlElement(name = "Telaio", required = true)
    protected String telaio;
    @XmlElement(name = "DataCarico", required = true)
    protected String dataCarico;
    @XmlElement(name = "DataScarico", required = true)
    protected String dataScarico;
    @XmlElement(name = "Variazione", required = true)
    protected String variazione;

    /**
     * Gets the value of the genere property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenere() {
        return genere;
    }

    /**
     * Sets the value of the genere property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenere(String value) {
        this.genere = value;
    }

    /**
     * Gets the value of the categoria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoria() {
        return categoria;
    }

    /**
     * Sets the value of the categoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoria(String value) {
        this.categoria = value;
    }

    /**
     * Gets the value of the anno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnno() {
        return anno;
    }

    /**
     * Sets the value of the anno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnno(String value) {
        this.anno = value;
    }

    /**
     * Gets the value of the marca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarca() {
        return marca;
    }

    /**
     * Sets the value of the marca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarca(String value) {
        this.marca = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipo(String value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the formaPossesso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormaPossesso() {
        return formaPossesso;
    }

    /**
     * Sets the value of the formaPossesso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormaPossesso(String value) {
        this.formaPossesso = value;
    }

    /**
     * Gets the value of the percPossessoMacch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercPossessoMacch() {
        return percPossessoMacch;
    }

    /**
     * Sets the value of the percPossessoMacch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercPossessoMacch(String value) {
        this.percPossessoMacch = value;
    }

    /**
     * Gets the value of the telaio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelaio() {
        return telaio;
    }

    /**
     * Sets the value of the telaio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelaio(String value) {
        this.telaio = value;
    }

    /**
     * Gets the value of the dataCarico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataCarico() {
        return dataCarico;
    }

    /**
     * Sets the value of the dataCarico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataCarico(String value) {
        this.dataCarico = value;
    }

    /**
     * Gets the value of the dataScarico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataScarico() {
        return dataScarico;
    }

    /**
     * Sets the value of the dataScarico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataScarico(String value) {
        this.dataScarico = value;
    }

    /**
     * Gets the value of the variazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariazione() {
        return variazione;
    }

    /**
     * Sets the value of the variazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariazione(String value) {
        this.variazione = value;
    }

}
