//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.csi.smranag.smrgaa.dto.jaxb.fascicolo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TotSupUtilizzata_QNAME = new QName("", "TotSupUtilizzata");
    private final static QName _CAP_QNAME = new QName("", "CAP");
    private final static QName _MotivoRichiesta_QNAME = new QName("", "MotivoRichiesta");
    private final static QName _TotCapiPropr_QNAME = new QName("", "TotCapiPropr");
    private final static QName _Foglio_QNAME = new QName("", "Foglio");
    private final static QName _Sub_QNAME = new QName("", "Sub");
    private final static QName _TitoloMacchine_QNAME = new QName("", "TitoloMacchine");
    private final static QName _Specie_QNAME = new QName("", "Specie");
    private final static QName _ValoreCheck_QNAME = new QName("", "valoreCheck");
    private final static QName _Valore3_QNAME = new QName("", "valore3");
    private final static QName _Telaio_QNAME = new QName("", "Telaio");
    private final static QName _NomeRiepilogo_QNAME = new QName("", "nomeRiepilogo");
    private final static QName _DataFirma_QNAME = new QName("", "DataFirma");
    private final static QName _SalTempoParziale_QNAME = new QName("", "SalTempoParziale");
    private final static QName _TitoloDocumenti_QNAME = new QName("", "TitoloDocumenti");
    private final static QName _EnteFascicolo_QNAME = new QName("", "EnteFascicolo");
    private final static QName _SupVitata_QNAME = new QName("", "SupVitata");
    private final static QName _SupAgron_QNAME = new QName("", "SupAgron");
    private final static QName _FormaConduzione_QNAME = new QName("", "FormaConduzione");
    private final static QName _SupUtilSec_QNAME = new QName("", "SupUtilSec");
    private final static QName _TotTempoPieno_QNAME = new QName("", "TotTempoPieno");
    private final static QName _SupGis_QNAME = new QName("", "SupGis");
    private final static QName _AnnoRiatt_QNAME = new QName("", "AnnoRiatt");
    private final static QName _Note_QNAME = new QName("", "Note");
    private final static QName _Variazione_QNAME = new QName("", "Variazione");
    private final static QName _TotAzoto_QNAME = new QName("", "TotAzoto");
    private final static QName _LegendaRot_QNAME = new QName("", "LegendaRot");
    private final static QName _Ute_QNAME = new QName("", "Ute");
    private final static QName _TitoloSoggetti_QNAME = new QName("", "TitoloSoggetti");
    private final static QName _IndirizzoEnte2_QNAME = new QName("", "IndirizzoEnte2");
    private final static QName _Sezione_QNAME = new QName("", "Sezione");
    private final static QName _AltreInfo_QNAME = new QName("", "AltreInfo");
    private final static QName _TitoloAssociazioni_QNAME = new QName("", "TitoloAssociazioni");
    private final static QName _TotSupSau_QNAME = new QName("", "TotSupSau");
    private final static QName _TitoloFabbricati_QNAME = new QName("", "TitoloFabbricati");
    private final static QName _LuogoFirma_QNAME = new QName("", "LuogoFirma");
    private final static QName _TitoloAllevamenti_QNAME = new QName("", "TitoloAllevamenti");
    private final static QName _FamTempoPieno_QNAME = new QName("", "FamTempoPieno");
    private final static QName _UnitaMisuraDimensione_QNAME = new QName("", "UnitaMisuraDimensione");
    private final static QName _Titolo2SezAnagrafica_QNAME = new QName("", "Titolo2sezAnagrafica");
    private final static QName _Nome_QNAME = new QName("", "Nome");
    private final static QName _Cond_QNAME = new QName("", "Cond");
    private final static QName _Titolo1SezAnagrafica_QNAME = new QName("", "Titolo1sezAnagrafica");
    private final static QName _Indirizzo_QNAME = new QName("", "Indirizzo");
    private final static QName _Sottoscritto_QNAME = new QName("", "Sottoscritto");
    private final static QName _Tipo_QNAME = new QName("", "Tipo");
    private final static QName _HeadChecklist_QNAME = new QName("", "HeadChecklist");
    private final static QName _TipoRiga_QNAME = new QName("", "tipoRiga");
    private final static QName _IndirizzoEnte1_QNAME = new QName("", "IndirizzoEnte1");
    private final static QName _Intestazione3_QNAME = new QName("", "intestazione3");
    private final static QName _TitoloTerreni_QNAME = new QName("", "TitoloTerreni");
    private final static QName _TitoloManodopera_QNAME = new QName("", "TitoloManodopera");
    private final static QName _Registro_QNAME = new QName("", "Registro");
    private final static QName _TitoloSezSoggetti_QNAME = new QName("", "TitoloSezSoggetti");
    private final static QName _FormaPossesso_QNAME = new QName("", "FormaPossesso");
    private final static QName _SezioneVuota_QNAME = new QName("", "SezioneVuota");
    private final static QName _Denominazione_QNAME = new QName("", "Denominazione");
    private final static QName _Valore4_QNAME = new QName("", "valore4");
    private final static QName _CicloOrtivo_QNAME = new QName("", "CicloOrtivo");
    private final static QName _Ateco_QNAME = new QName("", "Ateco");
    private final static QName _Genere_QNAME = new QName("", "Genere");
    private final static QName _Protocollo_QNAME = new QName("", "Protocollo");
    private final static QName _Istituto_QNAME = new QName("", "Istituto");
    private final static QName _LegendaVincoli_QNAME = new QName("", "LegendaVincoli");
    private final static QName _DataIngresso_QNAME = new QName("", "DataIngresso");
    private final static QName _Anno_QNAME = new QName("", "Anno");
    private final static QName _TitoloSezConti_QNAME = new QName("", "TitoloSezConti");
    private final static QName _TotCapiDetenuti_QNAME = new QName("", "TotCapiDetenuti");
    private final static QName _NrProt_QNAME = new QName("", "NrProt");
    private final static QName _Intestazione4_QNAME = new QName("", "intestazione4");
    private final static QName _CodiceEnte_QNAME = new QName("", "CodiceEnte");
    private final static QName _Cuaa_QNAME = new QName("", "Cuaa");
    private final static QName _Uso_QNAME = new QName("", "Uso");
    private final static QName _Sup_QNAME = new QName("", "Sup");
    private final static QName _IndirizzoSedeLeg_QNAME = new QName("", "IndirizzoSedeLeg");
    private final static QName _Intestazione1_QNAME = new QName("", "intestazione1");
    private final static QName _NoParticelle_QNAME = new QName("", "NoParticelle");
    private final static QName _ValoreDich_QNAME = new QName("", "valoreDich");
    private final static QName _Valore2_QNAME = new QName("", "valore2");
    private final static QName _Azienda_QNAME = new QName("", "Azienda");
    private final static QName _Descrizione_QNAME = new QName("", "Descrizione");
    private final static QName _Codice_QNAME = new QName("", "Codice");
    private final static QName _CodiceAsl_QNAME = new QName("", "CodiceAsl");
    private final static QName _CapiPropr_QNAME = new QName("", "CapiPropr");
    private final static QName _TitoloMotori_QNAME = new QName("", "TitoloMotori");
    private final static QName _TitoloUnitaVitate_QNAME = new QName("", "TitoloUnitaVitate");
    private final static QName _DataImpianto_QNAME = new QName("", "DataImpianto");
    private final static QName _Cicli_QNAME = new QName("", "Cicli");
    private final static QName _Irrigua_QNAME = new QName("", "Irrigua");
    private final static QName _TotTempoParziale_QNAME = new QName("", "TotTempoParziale");
    private final static QName _TipologiaAssicurativa_QNAME = new QName("", "TipologiaAssicurativa");
    private final static QName _Part_QNAME = new QName("", "Part");
    private final static QName _Targa_QNAME = new QName("", "Targa");
    private final static QName _CodiceFiscale_QNAME = new QName("", "CodiceFiscale");
    private final static QName _TotSupCatastale_QNAME = new QName("", "TotSupCatastale");
    private final static QName _LegendaIrrig_QNAME = new QName("", "LegendaIrrig");
    private final static QName _Categoria_QNAME = new QName("", "Categoria");
    private final static QName _SalTempoPieno_QNAME = new QName("", "SalTempoPieno");
    private final static QName _TitoloSezTitolare_QNAME = new QName("", "TitoloSezTitolare");
    private final static QName _Valore1_QNAME = new QName("", "valore1");
    private final static QName _DataUscita_QNAME = new QName("", "DataUscita");
    private final static QName _Marca_QNAME = new QName("", "Marca");
    private final static QName _Vitigno_QNAME = new QName("", "Vitigno");
    private final static QName _Vincoli_QNAME = new QName("", "Vincoli");
    private final static QName _Comune_QNAME = new QName("", "Comune");
    private final static QName _LuogoEData_QNAME = new QName("", "LuogoEData");
    private final static QName _Intestazione2_QNAME = new QName("", "intestazione2");
    private final static QName _Dimensione_QNAME = new QName("", "Dimensione");
    private final static QName _OrientamentoProduttivo_QNAME = new QName("", "OrientamentoProduttivo");
    private final static QName _Ruolo_QNAME = new QName("", "ruolo");
    private final static QName _DataCarico_QNAME = new QName("", "DataCarico");
    private final static QName _GiornateAnnue_QNAME = new QName("", "GiornateAnnue");
    private final static QName _FamTempoParziale_QNAME = new QName("", "FamTempoParziale");
    private final static QName _Oggetto_QNAME = new QName("", "Oggetto");
    private final static QName _DataFineRuolo_QNAME = new QName("", "DataFineRuolo");
    private final static QName _Azoto_QNAME = new QName("", "Azoto");
    private final static QName _Avventizi_QNAME = new QName("", "Avventizi");
    private final static QName _Titolo2_QNAME = new QName("", "Titolo2");
    private final static QName _Progr_QNAME = new QName("", "Progr");
    private final static QName _PercPossessoMacch_QNAME = new QName("", "PercPossessoMacch");
    private final static QName _Durata_QNAME = new QName("", "Durata");
    private final static QName _CognomeNome_QNAME = new QName("", "CognomeNome");
    private final static QName _Titolone_QNAME = new QName("", "Titolone");
    private final static QName _DataProt_QNAME = new QName("", "DataProt");
    private final static QName _Agenzia_QNAME = new QName("", "Agenzia");
    private final static QName _Iban_QNAME = new QName("", "Iban");
    private final static QName _Firmatario_QNAME = new QName("", "Firmatario");
    private final static QName _PartitaIva_QNAME = new QName("", "PartitaIva");
    private final static QName _Titolo1_QNAME = new QName("", "Titolo1");
    private final static QName _SottoCategoria_QNAME = new QName("", "SottoCategoria");
    private final static QName _InQualita_QNAME = new QName("", "InQualita");
    private final static QName _TipoProduzione_QNAME = new QName("", "TipoProduzione");
    private final static QName _Sottotitolo_QNAME = new QName("", "Sottotitolo");
    private final static QName _ColonneRiga_QNAME = new QName("", "colonneRiga");
    private final static QName _Titolo_QNAME = new QName("", "Titolo");
    private final static QName _DataInizioRuolo_QNAME = new QName("", "DataInizioRuolo");
    private final static QName _TitoloSezAssociazioni_QNAME = new QName("", "TitoloSezAssociazioni");
    private final static QName _HeadAllegati_QNAME = new QName("", "HeadAllegati");
    private final static QName _DataDich_QNAME = new QName("", "DataDich");
    private final static QName _CapiDetenuti_QNAME = new QName("", "CapiDetenuti");
    private final static QName _Tel_QNAME = new QName("", "Tel");
    private final static QName _TitoloUte_QNAME = new QName("", "TitoloUte");
    private final static QName _DataScarico_QNAME = new QName("", "DataScarico");
    private final static QName _HeadCondizionalita_QNAME = new QName("", "HeadCondizionalita");
    private final static QName _Visibility_QNAME = new QName("", "Visibility");
    private final static QName _LegendaPart_QNAME = new QName("", "LegendaPart");
    private final static QName _EtichettaFirma_QNAME = new QName("", "EtichettaFirma");
    private final static QName _Cognome_QNAME = new QName("", "Cognome");
    private final static QName _TotSupVite_QNAME = new QName("", "TotSupVite");
    private final static QName _SupUtil_QNAME = new QName("", "SupUtil");
    private final static QName _Idoneita_QNAME = new QName("", "Idoneita");
    private final static QName _Email_QNAME = new QName("", "email");
    private final static QName _Pec_QNAME = new QName("", "Pec");
    private final static QName _SupCatastale_QNAME = new QName("", "SupCatastale");
    private final static QName _MotivoDich_QNAME = new QName("", "MotivoDich");
    private final static QName _UsoSec_QNAME = new QName("", "UsoSec");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.csi.smranag.smrgaa.dto.jaxb.fascicolo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QuadroUnitaVitate }
     * 
     */
    public QuadroUnitaVitate createQuadroUnitaVitate() {
        return new QuadroUnitaVitate();
    }

    /**
     * Create an instance of {@link SezioneAnagrafica }
     * 
     */
    public SezioneAnagrafica createSezioneAnagrafica() {
        return new SezioneAnagrafica();
    }

    /**
     * Create an instance of {@link ElencoUTE }
     * 
     */
    public ElencoUTE createElencoUTE() {
        return new ElencoUTE();
    }

    /**
     * Create an instance of {@link QuadroMotori }
     * 
     */
    public QuadroMotori createQuadroMotori() {
        return new QuadroMotori();
    }

    /**
     * Create an instance of {@link SezioneSoggetti }
     * 
     */
    public SezioneSoggetti createSezioneSoggetti() {
        return new SezioneSoggetti();
    }

    /**
     * Create an instance of {@link ElencoCheck }
     * 
     */
    public ElencoCheck createElencoCheck() {
        return new ElencoCheck();
    }

    /**
     * Create an instance of {@link UTE }
     * 
     */
    public UTE createUTE() {
        return new UTE();
    }

    /**
     * Create an instance of {@link Allevamenti }
     * 
     */
    public Allevamenti createAllevamenti() {
        return new Allevamenti();
    }

    /**
     * Create an instance of {@link Particelle }
     * 
     */
    public Particelle createParticelle() {
        return new Particelle();
    }

    /**
     * Create an instance of {@link HeaderLandscape }
     * 
     */
    public HeaderLandscape createHeaderLandscape() {
        return new HeaderLandscape();
    }

    /**
     * Create an instance of {@link RigaUv }
     * 
     */
    public RigaUv createRigaUv() {
        return new RigaUv();
    }

    /**
     * Create an instance of {@link Macchina }
     * 
     */
    public Macchina createMacchina() {
        return new Macchina();
    }

    /**
     * Create an instance of {@link RigaTotaliAllev }
     * 
     */
    public RigaTotaliAllev createRigaTotaliAllev() {
        return new RigaTotaliAllev();
    }

    /**
     * Create an instance of {@link RigaRiepilogoUv }
     * 
     */
    public RigaRiepilogoUv createRigaRiepilogoUv() {
        return new RigaRiepilogoUv();
    }

    /**
     * Create an instance of {@link Riepilogo }
     * 
     */
    public Riepilogo createRiepilogo() {
        return new Riepilogo();
    }

    /**
     * Create an instance of {@link MacchineVar }
     * 
     */
    public MacchineVar createMacchineVar() {
        return new MacchineVar();
    }

    /**
     * Create an instance of {@link RigaTotaliUv }
     * 
     */
    public RigaTotaliUv createRigaTotaliUv() {
        return new RigaTotaliUv();
    }

    /**
     * Create an instance of {@link Associazioni }
     * 
     */
    public Associazioni createAssociazioni() {
        return new Associazioni();
    }

    /**
     * Create an instance of {@link BloccoConCheck2 }
     * 
     */
    public BloccoConCheck2 createBloccoConCheck2() {
        return new BloccoConCheck2();
    }

    /**
     * Create an instance of {@link Fascicolo }
     * 
     */
    public Fascicolo createFascicolo() {
        return new Fascicolo();
    }

    /**
     * Create an instance of {@link SezioneAssociazioni }
     * 
     */
    public SezioneAssociazioni createSezioneAssociazioni() {
        return new SezioneAssociazioni();
    }

    /**
     * Create an instance of {@link Allevamento }
     * 
     */
    public Allevamento createAllevamento() {
        return new Allevamento();
    }

    /**
     * Create an instance of {@link BloccoConCheck }
     * 
     */
    public BloccoConCheck createBloccoConCheck() {
        return new BloccoConCheck();
    }

    /**
     * Create an instance of {@link QuadroAllevamenti }
     * 
     */
    public QuadroAllevamenti createQuadroAllevamenti() {
        return new QuadroAllevamenti();
    }

    /**
     * Create an instance of {@link AllegatiNormali }
     * 
     */
    public AllegatiNormali createAllegatiNormali() {
        return new AllegatiNormali();
    }

    /**
     * Create an instance of {@link RiepilogoUv }
     * 
     */
    public RiepilogoUv createRiepilogoUv() {
        return new RiepilogoUv();
    }

    /**
     * Create an instance of {@link QuadroUte }
     * 
     */
    public QuadroUte createQuadroUte() {
        return new QuadroUte();
    }

    /**
     * Create an instance of {@link Motori }
     * 
     */
    public Motori createMotori() {
        return new Motori();
    }

    /**
     * Create an instance of {@link Associazione }
     * 
     */
    public Associazione createAssociazione() {
        return new Associazione();
    }

    /**
     * Create an instance of {@link Documento }
     * 
     */
    public Documento createDocumento() {
        return new Documento();
    }

    /**
     * Create an instance of {@link Associata }
     * 
     */
    public Associata createAssociata() {
        return new Associata();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Dichiarazione }
     * 
     */
    public Dichiarazione createDichiarazione() {
        return new Dichiarazione();
    }

    /**
     * Create an instance of {@link Fabbricato }
     * 
     */
    public Fabbricato createFabbricato() {
        return new Fabbricato();
    }

    /**
     * Create an instance of {@link RiepiloghiUv }
     * 
     */
    public RiepiloghiUv createRiepiloghiUv() {
        return new RiepiloghiUv();
    }

    /**
     * Create an instance of {@link QuadroVariazioneMotori }
     * 
     */
    public QuadroVariazioneMotori createQuadroVariazioneMotori() {
        return new QuadroVariazioneMotori();
    }

    /**
     * Create an instance of {@link Riepiloghi }
     * 
     */
    public Riepiloghi createRiepiloghi() {
        return new Riepiloghi();
    }

    /**
     * Create an instance of {@link RigaCapi }
     * 
     */
    public RigaCapi createRigaCapi() {
        return new RigaCapi();
    }

    /**
     * Create an instance of {@link BloccoFinale }
     * 
     */
    public BloccoFinale createBloccoFinale() {
        return new BloccoFinale();
    }

    /**
     * Create an instance of {@link MacchinaVar }
     * 
     */
    public MacchinaVar createMacchinaVar() {
        return new MacchinaVar();
    }

    /**
     * Create an instance of {@link AltroSoggetto }
     * 
     */
    public AltroSoggetto createAltroSoggetto() {
        return new AltroSoggetto();
    }

    /**
     * Create an instance of {@link RigheRiepilogoUv }
     * 
     */
    public RigheRiepilogoUv createRigheRiepilogoUv() {
        return new RigheRiepilogoUv();
    }

    /**
     * Create an instance of {@link Firma2 }
     * 
     */
    public Firma2 createFirma2() {
        return new Firma2();
    }

    /**
     * Create an instance of {@link DichiarazioneCheck }
     * 
     */
    public DichiarazioneCheck createDichiarazioneCheck() {
        return new DichiarazioneCheck();
    }

    /**
     * Create an instance of {@link QuadroDocumenti }
     * 
     */
    public QuadroDocumenti createQuadroDocumenti() {
        return new QuadroDocumenti();
    }

    /**
     * Create an instance of {@link Soggetti }
     * 
     */
    public Soggetti createSoggetti() {
        return new Soggetti();
    }

    /**
     * Create an instance of {@link Particella }
     * 
     */
    public Particella createParticella() {
        return new Particella();
    }

    /**
     * Create an instance of {@link UnitaVitate }
     * 
     */
    public UnitaVitate createUnitaVitate() {
        return new UnitaVitate();
    }

    /**
     * Create an instance of {@link ParticellaFab }
     * 
     */
    public ParticellaFab createParticellaFab() {
        return new ParticellaFab();
    }

    /**
     * Create an instance of {@link QuadroAssociazioni }
     * 
     */
    public QuadroAssociazioni createQuadroAssociazioni() {
        return new QuadroAssociazioni();
    }

    /**
     * Create an instance of {@link ElencoCategorie }
     * 
     */
    public ElencoCategorie createElencoCategorie() {
        return new ElencoCategorie();
    }

    /**
     * Create an instance of {@link Soggetto }
     * 
     */
    public Soggetto createSoggetto() {
        return new Soggetto();
    }

    /**
     * Create an instance of {@link QuadroTerreni }
     * 
     */
    public QuadroTerreni createQuadroTerreni() {
        return new QuadroTerreni();
    }

    /**
     * Create an instance of {@link Firma }
     * 
     */
    public Firma createFirma() {
        return new Firma();
    }

    /**
     * Create an instance of {@link Documenti }
     * 
     */
    public Documenti createDocumenti() {
        return new Documenti();
    }

    /**
     * Create an instance of {@link Conto }
     * 
     */
    public Conto createConto() {
        return new Conto();
    }

    /**
     * Create an instance of {@link RigheRiepilogo }
     * 
     */
    public RigheRiepilogo createRigheRiepilogo() {
        return new RigheRiepilogo();
    }

    /**
     * Create an instance of {@link Particellare }
     * 
     */
    public Particellare createParticellare() {
        return new Particellare();
    }

    /**
     * Create an instance of {@link SezioneConti }
     * 
     */
    public SezioneConti createSezioneConti() {
        return new SezioneConti();
    }

    /**
     * Create an instance of {@link SoggettiCollegati }
     * 
     */
    public SoggettiCollegati createSoggettiCollegati() {
        return new SoggettiCollegati();
    }

    /**
     * Create an instance of {@link HeaderAllegati }
     * 
     */
    public HeaderAllegati createHeaderAllegati() {
        return new HeaderAllegati();
    }

    /**
     * Create an instance of {@link ElencoParticelle }
     * 
     */
    public ElencoParticelle createElencoParticelle() {
        return new ElencoParticelle();
    }

    /**
     * Create an instance of {@link ElencoDichiarazioni }
     * 
     */
    public ElencoDichiarazioni createElencoDichiarazioni() {
        return new ElencoDichiarazioni();
    }

    /**
     * Create an instance of {@link PrimoBlocco }
     * 
     */
    public PrimoBlocco createPrimoBlocco() {
        return new PrimoBlocco();
    }

    /**
     * Create an instance of {@link QuadroManodopera }
     * 
     */
    public QuadroManodopera createQuadroManodopera() {
        return new QuadroManodopera();
    }

    /**
     * Create an instance of {@link IntroRichVar }
     * 
     */
    public IntroRichVar createIntroRichVar() {
        return new IntroRichVar();
    }

    /**
     * Create an instance of {@link QuadroA }
     * 
     */
    public QuadroA createQuadroA() {
        return new QuadroA();
    }

    /**
     * Create an instance of {@link Dichiarazioni }
     * 
     */
    public Dichiarazioni createDichiarazioni() {
        return new Dichiarazioni();
    }

    /**
     * Create an instance of {@link Associate }
     * 
     */
    public Associate createAssociate() {
        return new Associate();
    }

    /**
     * Create an instance of {@link SecondoBlocco }
     * 
     */
    public SecondoBlocco createSecondoBlocco() {
        return new SecondoBlocco();
    }

    /**
     * Create an instance of {@link RigaTotali }
     * 
     */
    public RigaTotali createRigaTotali() {
        return new RigaTotali();
    }

    /**
     * Create an instance of {@link RigaRiepilogo }
     * 
     */
    public RigaRiepilogo createRigaRiepilogo() {
        return new RigaRiepilogo();
    }

    /**
     * Create an instance of {@link ContiCorrenti }
     * 
     */
    public ContiCorrenti createContiCorrenti() {
        return new ContiCorrenti();
    }

    /**
     * Create an instance of {@link SezioneTitolare }
     * 
     */
    public SezioneTitolare createSezioneTitolare() {
        return new SezioneTitolare();
    }

    /**
     * Create an instance of {@link QuadroSoggetti }
     * 
     */
    public QuadroSoggetti createQuadroSoggetti() {
        return new QuadroSoggetti();
    }

    /**
     * Create an instance of {@link QuadroFabbricati }
     * 
     */
    public QuadroFabbricati createQuadroFabbricati() {
        return new QuadroFabbricati();
    }

    /**
     * Create an instance of {@link Castelletto }
     * 
     */
    public Castelletto createCastelletto() {
        return new Castelletto();
    }

    /**
     * Create an instance of {@link Allegati }
     * 
     */
    public Allegati createAllegati() {
        return new Allegati();
    }

    /**
     * Create an instance of {@link AllegatiCondizionalita }
     * 
     */
    public AllegatiCondizionalita createAllegatiCondizionalita() {
        return new AllegatiCondizionalita();
    }

    /**
     * Create an instance of {@link Fabbricati }
     * 
     */
    public Fabbricati createFabbricati() {
        return new Fabbricati();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotSupUtilizzata")
    public JAXBElement<String> createTotSupUtilizzata(String value) {
        return new JAXBElement<String>(_TotSupUtilizzata_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CAP")
    public JAXBElement<String> createCAP(String value) {
        return new JAXBElement<String>(_CAP_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MotivoRichiesta")
    public JAXBElement<String> createMotivoRichiesta(String value) {
        return new JAXBElement<String>(_MotivoRichiesta_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotCapiPropr")
    public JAXBElement<String> createTotCapiPropr(String value) {
        return new JAXBElement<String>(_TotCapiPropr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Foglio")
    public JAXBElement<String> createFoglio(String value) {
        return new JAXBElement<String>(_Foglio_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Sub")
    public JAXBElement<String> createSub(String value) {
        return new JAXBElement<String>(_Sub_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitoloMacchine")
    public JAXBElement<String> createTitoloMacchine(String value) {
        return new JAXBElement<String>(_TitoloMacchine_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Specie")
    public JAXBElement<String> createSpecie(String value) {
        return new JAXBElement<String>(_Specie_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "valoreCheck")
    public JAXBElement<BigInteger> createValoreCheck(BigInteger value) {
        return new JAXBElement<BigInteger>(_ValoreCheck_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "valore3")
    public JAXBElement<String> createValore3(String value) {
        return new JAXBElement<String>(_Valore3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Telaio")
    public JAXBElement<String> createTelaio(String value) {
        return new JAXBElement<String>(_Telaio_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nomeRiepilogo")
    public JAXBElement<String> createNomeRiepilogo(String value) {
        return new JAXBElement<String>(_NomeRiepilogo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataFirma")
    public JAXBElement<String> createDataFirma(String value) {
        return new JAXBElement<String>(_DataFirma_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SalTempoParziale")
    public JAXBElement<String> createSalTempoParziale(String value) {
        return new JAXBElement<String>(_SalTempoParziale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitoloDocumenti")
    public JAXBElement<String> createTitoloDocumenti(String value) {
        return new JAXBElement<String>(_TitoloDocumenti_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EnteFascicolo")
    public JAXBElement<String> createEnteFascicolo(String value) {
        return new JAXBElement<String>(_EnteFascicolo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SupVitata")
    public JAXBElement<String> createSupVitata(String value) {
        return new JAXBElement<String>(_SupVitata_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SupAgron")
    public JAXBElement<String> createSupAgron(String value) {
        return new JAXBElement<String>(_SupAgron_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FormaConduzione")
    public JAXBElement<String> createFormaConduzione(String value) {
        return new JAXBElement<String>(_FormaConduzione_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SupUtilSec")
    public JAXBElement<String> createSupUtilSec(String value) {
        return new JAXBElement<String>(_SupUtilSec_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotTempoPieno")
    public JAXBElement<String> createTotTempoPieno(String value) {
        return new JAXBElement<String>(_TotTempoPieno_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SupGis")
    public JAXBElement<String> createSupGis(String value) {
        return new JAXBElement<String>(_SupGis_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AnnoRiatt")
    public JAXBElement<String> createAnnoRiatt(String value) {
        return new JAXBElement<String>(_AnnoRiatt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Note")
    public JAXBElement<String> createNote(String value) {
        return new JAXBElement<String>(_Note_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Variazione")
    public JAXBElement<String> createVariazione(String value) {
        return new JAXBElement<String>(_Variazione_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotAzoto")
    public JAXBElement<String> createTotAzoto(String value) {
        return new JAXBElement<String>(_TotAzoto_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LegendaRot")
    public JAXBElement<String> createLegendaRot(String value) {
        return new JAXBElement<String>(_LegendaRot_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Ute")
    public JAXBElement<String> createUte(String value) {
        return new JAXBElement<String>(_Ute_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitoloSoggetti")
    public JAXBElement<String> createTitoloSoggetti(String value) {
        return new JAXBElement<String>(_TitoloSoggetti_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IndirizzoEnte2")
    public JAXBElement<String> createIndirizzoEnte2(String value) {
        return new JAXBElement<String>(_IndirizzoEnte2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Sezione")
    public JAXBElement<String> createSezione(String value) {
        return new JAXBElement<String>(_Sezione_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AltreInfo")
    public JAXBElement<String> createAltreInfo(String value) {
        return new JAXBElement<String>(_AltreInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitoloAssociazioni")
    public JAXBElement<String> createTitoloAssociazioni(String value) {
        return new JAXBElement<String>(_TitoloAssociazioni_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotSupSau")
    public JAXBElement<String> createTotSupSau(String value) {
        return new JAXBElement<String>(_TotSupSau_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitoloFabbricati")
    public JAXBElement<String> createTitoloFabbricati(String value) {
        return new JAXBElement<String>(_TitoloFabbricati_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LuogoFirma")
    public JAXBElement<String> createLuogoFirma(String value) {
        return new JAXBElement<String>(_LuogoFirma_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitoloAllevamenti")
    public JAXBElement<String> createTitoloAllevamenti(String value) {
        return new JAXBElement<String>(_TitoloAllevamenti_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FamTempoPieno")
    public JAXBElement<String> createFamTempoPieno(String value) {
        return new JAXBElement<String>(_FamTempoPieno_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UnitaMisuraDimensione")
    public JAXBElement<String> createUnitaMisuraDimensione(String value) {
        return new JAXBElement<String>(_UnitaMisuraDimensione_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Titolo2sezAnagrafica")
    public JAXBElement<String> createTitolo2SezAnagrafica(String value) {
        return new JAXBElement<String>(_Titolo2SezAnagrafica_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Nome")
    public JAXBElement<String> createNome(String value) {
        return new JAXBElement<String>(_Nome_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Cond")
    public JAXBElement<String> createCond(String value) {
        return new JAXBElement<String>(_Cond_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Titolo1sezAnagrafica")
    public JAXBElement<String> createTitolo1SezAnagrafica(String value) {
        return new JAXBElement<String>(_Titolo1SezAnagrafica_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Indirizzo")
    public JAXBElement<String> createIndirizzo(String value) {
        return new JAXBElement<String>(_Indirizzo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Sottoscritto")
    public JAXBElement<String> createSottoscritto(String value) {
        return new JAXBElement<String>(_Sottoscritto_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Tipo")
    public JAXBElement<String> createTipo(String value) {
        return new JAXBElement<String>(_Tipo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HeadChecklist")
    public JAXBElement<Boolean> createHeadChecklist(Boolean value) {
        return new JAXBElement<Boolean>(_HeadChecklist_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tipoRiga")
    public JAXBElement<String> createTipoRiga(String value) {
        return new JAXBElement<String>(_TipoRiga_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IndirizzoEnte1")
    public JAXBElement<String> createIndirizzoEnte1(String value) {
        return new JAXBElement<String>(_IndirizzoEnte1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "intestazione3")
    public JAXBElement<String> createIntestazione3(String value) {
        return new JAXBElement<String>(_Intestazione3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitoloTerreni")
    public JAXBElement<String> createTitoloTerreni(String value) {
        return new JAXBElement<String>(_TitoloTerreni_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitoloManodopera")
    public JAXBElement<String> createTitoloManodopera(String value) {
        return new JAXBElement<String>(_TitoloManodopera_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Registro")
    public JAXBElement<String> createRegistro(String value) {
        return new JAXBElement<String>(_Registro_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitoloSezSoggetti")
    public JAXBElement<String> createTitoloSezSoggetti(String value) {
        return new JAXBElement<String>(_TitoloSezSoggetti_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FormaPossesso")
    public JAXBElement<String> createFormaPossesso(String value) {
        return new JAXBElement<String>(_FormaPossesso_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SezioneVuota")
    public JAXBElement<Boolean> createSezioneVuota(Boolean value) {
        return new JAXBElement<Boolean>(_SezioneVuota_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Denominazione")
    public JAXBElement<String> createDenominazione(String value) {
        return new JAXBElement<String>(_Denominazione_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "valore4")
    public JAXBElement<String> createValore4(String value) {
        return new JAXBElement<String>(_Valore4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CicloOrtivo")
    public JAXBElement<String> createCicloOrtivo(String value) {
        return new JAXBElement<String>(_CicloOrtivo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Ateco")
    public JAXBElement<String> createAteco(String value) {
        return new JAXBElement<String>(_Ateco_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Genere")
    public JAXBElement<String> createGenere(String value) {
        return new JAXBElement<String>(_Genere_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Protocollo")
    public JAXBElement<String> createProtocollo(String value) {
        return new JAXBElement<String>(_Protocollo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Istituto")
    public JAXBElement<String> createIstituto(String value) {
        return new JAXBElement<String>(_Istituto_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LegendaVincoli")
    public JAXBElement<String> createLegendaVincoli(String value) {
        return new JAXBElement<String>(_LegendaVincoli_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataIngresso")
    public JAXBElement<String> createDataIngresso(String value) {
        return new JAXBElement<String>(_DataIngresso_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Anno")
    public JAXBElement<String> createAnno(String value) {
        return new JAXBElement<String>(_Anno_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitoloSezConti")
    public JAXBElement<String> createTitoloSezConti(String value) {
        return new JAXBElement<String>(_TitoloSezConti_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotCapiDetenuti")
    public JAXBElement<String> createTotCapiDetenuti(String value) {
        return new JAXBElement<String>(_TotCapiDetenuti_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NrProt")
    public JAXBElement<String> createNrProt(String value) {
        return new JAXBElement<String>(_NrProt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "intestazione4")
    public JAXBElement<String> createIntestazione4(String value) {
        return new JAXBElement<String>(_Intestazione4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodiceEnte")
    public JAXBElement<String> createCodiceEnte(String value) {
        return new JAXBElement<String>(_CodiceEnte_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Cuaa")
    public JAXBElement<String> createCuaa(String value) {
        return new JAXBElement<String>(_Cuaa_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Uso")
    public JAXBElement<String> createUso(String value) {
        return new JAXBElement<String>(_Uso_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Sup")
    public JAXBElement<String> createSup(String value) {
        return new JAXBElement<String>(_Sup_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IndirizzoSedeLeg")
    public JAXBElement<String> createIndirizzoSedeLeg(String value) {
        return new JAXBElement<String>(_IndirizzoSedeLeg_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "intestazione1")
    public JAXBElement<String> createIntestazione1(String value) {
        return new JAXBElement<String>(_Intestazione1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NoParticelle")
    public JAXBElement<Boolean> createNoParticelle(Boolean value) {
        return new JAXBElement<Boolean>(_NoParticelle_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "valoreDich")
    public JAXBElement<String> createValoreDich(String value) {
        return new JAXBElement<String>(_ValoreDich_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "valore2")
    public JAXBElement<String> createValore2(String value) {
        return new JAXBElement<String>(_Valore2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Azienda")
    public JAXBElement<String> createAzienda(String value) {
        return new JAXBElement<String>(_Azienda_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Descrizione")
    public JAXBElement<String> createDescrizione(String value) {
        return new JAXBElement<String>(_Descrizione_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Codice")
    public JAXBElement<String> createCodice(String value) {
        return new JAXBElement<String>(_Codice_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodiceAsl")
    public JAXBElement<String> createCodiceAsl(String value) {
        return new JAXBElement<String>(_CodiceAsl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CapiPropr")
    public JAXBElement<String> createCapiPropr(String value) {
        return new JAXBElement<String>(_CapiPropr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitoloMotori")
    public JAXBElement<String> createTitoloMotori(String value) {
        return new JAXBElement<String>(_TitoloMotori_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitoloUnitaVitate")
    public JAXBElement<String> createTitoloUnitaVitate(String value) {
        return new JAXBElement<String>(_TitoloUnitaVitate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataImpianto")
    public JAXBElement<String> createDataImpianto(String value) {
        return new JAXBElement<String>(_DataImpianto_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Cicli")
    public JAXBElement<String> createCicli(String value) {
        return new JAXBElement<String>(_Cicli_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Irrigua")
    public JAXBElement<String> createIrrigua(String value) {
        return new JAXBElement<String>(_Irrigua_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotTempoParziale")
    public JAXBElement<String> createTotTempoParziale(String value) {
        return new JAXBElement<String>(_TotTempoParziale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TipologiaAssicurativa")
    public JAXBElement<String> createTipologiaAssicurativa(String value) {
        return new JAXBElement<String>(_TipologiaAssicurativa_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Part")
    public JAXBElement<String> createPart(String value) {
        return new JAXBElement<String>(_Part_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Targa")
    public JAXBElement<String> createTarga(String value) {
        return new JAXBElement<String>(_Targa_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodiceFiscale")
    public JAXBElement<String> createCodiceFiscale(String value) {
        return new JAXBElement<String>(_CodiceFiscale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotSupCatastale")
    public JAXBElement<String> createTotSupCatastale(String value) {
        return new JAXBElement<String>(_TotSupCatastale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LegendaIrrig")
    public JAXBElement<String> createLegendaIrrig(String value) {
        return new JAXBElement<String>(_LegendaIrrig_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Categoria")
    public JAXBElement<String> createCategoria(String value) {
        return new JAXBElement<String>(_Categoria_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SalTempoPieno")
    public JAXBElement<String> createSalTempoPieno(String value) {
        return new JAXBElement<String>(_SalTempoPieno_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitoloSezTitolare")
    public JAXBElement<String> createTitoloSezTitolare(String value) {
        return new JAXBElement<String>(_TitoloSezTitolare_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "valore1")
    public JAXBElement<String> createValore1(String value) {
        return new JAXBElement<String>(_Valore1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataUscita")
    public JAXBElement<String> createDataUscita(String value) {
        return new JAXBElement<String>(_DataUscita_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Marca")
    public JAXBElement<String> createMarca(String value) {
        return new JAXBElement<String>(_Marca_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Vitigno")
    public JAXBElement<String> createVitigno(String value) {
        return new JAXBElement<String>(_Vitigno_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Vincoli")
    public JAXBElement<String> createVincoli(String value) {
        return new JAXBElement<String>(_Vincoli_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Comune")
    public JAXBElement<String> createComune(String value) {
        return new JAXBElement<String>(_Comune_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LuogoEData")
    public JAXBElement<String> createLuogoEData(String value) {
        return new JAXBElement<String>(_LuogoEData_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "intestazione2")
    public JAXBElement<String> createIntestazione2(String value) {
        return new JAXBElement<String>(_Intestazione2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Dimensione")
    public JAXBElement<String> createDimensione(String value) {
        return new JAXBElement<String>(_Dimensione_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OrientamentoProduttivo")
    public JAXBElement<String> createOrientamentoProduttivo(String value) {
        return new JAXBElement<String>(_OrientamentoProduttivo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ruolo")
    public JAXBElement<String> createRuolo(String value) {
        return new JAXBElement<String>(_Ruolo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataCarico")
    public JAXBElement<String> createDataCarico(String value) {
        return new JAXBElement<String>(_DataCarico_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GiornateAnnue")
    public JAXBElement<String> createGiornateAnnue(String value) {
        return new JAXBElement<String>(_GiornateAnnue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FamTempoParziale")
    public JAXBElement<String> createFamTempoParziale(String value) {
        return new JAXBElement<String>(_FamTempoParziale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Oggetto")
    public JAXBElement<String> createOggetto(String value) {
        return new JAXBElement<String>(_Oggetto_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataFineRuolo")
    public JAXBElement<String> createDataFineRuolo(String value) {
        return new JAXBElement<String>(_DataFineRuolo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Azoto")
    public JAXBElement<String> createAzoto(String value) {
        return new JAXBElement<String>(_Azoto_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Avventizi")
    public JAXBElement<String> createAvventizi(String value) {
        return new JAXBElement<String>(_Avventizi_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Titolo2")
    public JAXBElement<String> createTitolo2(String value) {
        return new JAXBElement<String>(_Titolo2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Progr")
    public JAXBElement<String> createProgr(String value) {
        return new JAXBElement<String>(_Progr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PercPossessoMacch")
    public JAXBElement<String> createPercPossessoMacch(String value) {
        return new JAXBElement<String>(_PercPossessoMacch_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Durata")
    public JAXBElement<String> createDurata(String value) {
        return new JAXBElement<String>(_Durata_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CognomeNome")
    public JAXBElement<String> createCognomeNome(String value) {
        return new JAXBElement<String>(_CognomeNome_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Titolone")
    public JAXBElement<String> createTitolone(String value) {
        return new JAXBElement<String>(_Titolone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataProt")
    public JAXBElement<String> createDataProt(String value) {
        return new JAXBElement<String>(_DataProt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Agenzia")
    public JAXBElement<String> createAgenzia(String value) {
        return new JAXBElement<String>(_Agenzia_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Iban")
    public JAXBElement<String> createIban(String value) {
        return new JAXBElement<String>(_Iban_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Firmatario")
    public JAXBElement<String> createFirmatario(String value) {
        return new JAXBElement<String>(_Firmatario_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PartitaIva")
    public JAXBElement<String> createPartitaIva(String value) {
        return new JAXBElement<String>(_PartitaIva_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Titolo1")
    public JAXBElement<String> createTitolo1(String value) {
        return new JAXBElement<String>(_Titolo1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SottoCategoria")
    public JAXBElement<String> createSottoCategoria(String value) {
        return new JAXBElement<String>(_SottoCategoria_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InQualita")
    public JAXBElement<String> createInQualita(String value) {
        return new JAXBElement<String>(_InQualita_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TipoProduzione")
    public JAXBElement<String> createTipoProduzione(String value) {
        return new JAXBElement<String>(_TipoProduzione_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Sottotitolo")
    public JAXBElement<String> createSottotitolo(String value) {
        return new JAXBElement<String>(_Sottotitolo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "colonneRiga")
    public JAXBElement<BigInteger> createColonneRiga(BigInteger value) {
        return new JAXBElement<BigInteger>(_ColonneRiga_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Titolo")
    public JAXBElement<String> createTitolo(String value) {
        return new JAXBElement<String>(_Titolo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataInizioRuolo")
    public JAXBElement<String> createDataInizioRuolo(String value) {
        return new JAXBElement<String>(_DataInizioRuolo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitoloSezAssociazioni")
    public JAXBElement<String> createTitoloSezAssociazioni(String value) {
        return new JAXBElement<String>(_TitoloSezAssociazioni_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HeadAllegati")
    public JAXBElement<Boolean> createHeadAllegati(Boolean value) {
        return new JAXBElement<Boolean>(_HeadAllegati_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataDich")
    public JAXBElement<String> createDataDich(String value) {
        return new JAXBElement<String>(_DataDich_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CapiDetenuti")
    public JAXBElement<String> createCapiDetenuti(String value) {
        return new JAXBElement<String>(_CapiDetenuti_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Tel")
    public JAXBElement<String> createTel(String value) {
        return new JAXBElement<String>(_Tel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitoloUte")
    public JAXBElement<String> createTitoloUte(String value) {
        return new JAXBElement<String>(_TitoloUte_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataScarico")
    public JAXBElement<String> createDataScarico(String value) {
        return new JAXBElement<String>(_DataScarico_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HeadCondizionalita")
    public JAXBElement<Boolean> createHeadCondizionalita(Boolean value) {
        return new JAXBElement<Boolean>(_HeadCondizionalita_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Visibility")
    public JAXBElement<Boolean> createVisibility(Boolean value) {
        return new JAXBElement<Boolean>(_Visibility_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LegendaPart")
    public JAXBElement<String> createLegendaPart(String value) {
        return new JAXBElement<String>(_LegendaPart_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EtichettaFirma")
    public JAXBElement<String> createEtichettaFirma(String value) {
        return new JAXBElement<String>(_EtichettaFirma_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Cognome")
    public JAXBElement<String> createCognome(String value) {
        return new JAXBElement<String>(_Cognome_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotSupVite")
    public JAXBElement<String> createTotSupVite(String value) {
        return new JAXBElement<String>(_TotSupVite_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SupUtil")
    public JAXBElement<String> createSupUtil(String value) {
        return new JAXBElement<String>(_SupUtil_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Idoneita")
    public JAXBElement<String> createIdoneita(String value) {
        return new JAXBElement<String>(_Idoneita_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Pec")
    public JAXBElement<String> createPec(String value) {
        return new JAXBElement<String>(_Pec_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SupCatastale")
    public JAXBElement<String> createSupCatastale(String value) {
        return new JAXBElement<String>(_SupCatastale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MotivoDich")
    public JAXBElement<String> createMotivoDich(String value) {
        return new JAXBElement<String>(_MotivoDich_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UsoSec")
    public JAXBElement<String> createUsoSec(String value) {
        return new JAXBElement<String>(_UsoSec_QNAME, String.class, null, value);
    }

}
