//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SezioneVuota"/>
 *         &lt;element ref="{}Visibility"/>
 *         &lt;element ref="{}ElencoParticelle"/>
 *         &lt;element ref="{}RigaTotali"/>
 *         &lt;element ref="{}LegendaPart"/>
 *         &lt;element ref="{}LegendaRot"/>
 *         &lt;element ref="{}LegendaIrrig"/>
 *         &lt;element ref="{}LegendaVincoli"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sezioneVuota",
    "visibility",
    "elencoParticelle",
    "rigaTotali",
    "legendaPart",
    "legendaRot",
    "legendaIrrig",
    "legendaVincoli"
})
@XmlRootElement(name = "Particellare")
public class Particellare {

    @XmlElement(name = "SezioneVuota")
    protected boolean sezioneVuota;
    @XmlElement(name = "Visibility")
    protected boolean visibility;
    @XmlElement(name = "ElencoParticelle", required = true)
    protected ElencoParticelle elencoParticelle;
    @XmlElement(name = "RigaTotali", required = true)
    protected RigaTotali rigaTotali;
    @XmlElement(name = "LegendaPart", required = true)
    protected String legendaPart;
    @XmlElement(name = "LegendaRot", required = true)
    protected String legendaRot;
    @XmlElement(name = "LegendaIrrig", required = true)
    protected String legendaIrrig;
    @XmlElement(name = "LegendaVincoli", required = true)
    protected String legendaVincoli;

    /**
     * Gets the value of the sezioneVuota property.
     * 
     */
    public boolean isSezioneVuota() {
        return sezioneVuota;
    }

    /**
     * Sets the value of the sezioneVuota property.
     * 
     */
    public void setSezioneVuota(boolean value) {
        this.sezioneVuota = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     */
    public boolean isVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     */
    public void setVisibility(boolean value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the elencoParticelle property.
     * 
     * @return
     *     possible object is
     *     {@link ElencoParticelle }
     *     
     */
    public ElencoParticelle getElencoParticelle() {
        return elencoParticelle;
    }

    /**
     * Sets the value of the elencoParticelle property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElencoParticelle }
     *     
     */
    public void setElencoParticelle(ElencoParticelle value) {
        this.elencoParticelle = value;
    }

    /**
     * Gets the value of the rigaTotali property.
     * 
     * @return
     *     possible object is
     *     {@link RigaTotali }
     *     
     */
    public RigaTotali getRigaTotali() {
        return rigaTotali;
    }

    /**
     * Sets the value of the rigaTotali property.
     * 
     * @param value
     *     allowed object is
     *     {@link RigaTotali }
     *     
     */
    public void setRigaTotali(RigaTotali value) {
        this.rigaTotali = value;
    }

    /**
     * Gets the value of the legendaPart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegendaPart() {
        return legendaPart;
    }

    /**
     * Sets the value of the legendaPart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegendaPart(String value) {
        this.legendaPart = value;
    }

    /**
     * Gets the value of the legendaRot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegendaRot() {
        return legendaRot;
    }

    /**
     * Sets the value of the legendaRot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegendaRot(String value) {
        this.legendaRot = value;
    }

    /**
     * Gets the value of the legendaIrrig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegendaIrrig() {
        return legendaIrrig;
    }

    /**
     * Sets the value of the legendaIrrig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegendaIrrig(String value) {
        this.legendaIrrig = value;
    }

    /**
     * Gets the value of the legendaVincoli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegendaVincoli() {
        return legendaVincoli;
    }

    /**
     * Sets the value of the legendaVincoli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegendaVincoli(String value) {
        this.legendaVincoli = value;
    }

}
