//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}NoParticelle"/>
 *         &lt;element ref="{}ParticellaFab" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "noParticelle",
    "particellaFab"
})
@XmlRootElement(name = "Particelle")
public class Particelle {

    @XmlElement(name = "NoParticelle")
    protected boolean noParticelle;
    @XmlElement(name = "ParticellaFab", required = true)
    protected List<ParticellaFab> particellaFab;

    /**
     * Gets the value of the noParticelle property.
     * 
     */
    public boolean isNoParticelle() {
        return noParticelle;
    }

    /**
     * Sets the value of the noParticelle property.
     * 
     */
    public void setNoParticelle(boolean value) {
        this.noParticelle = value;
    }

    /**
     * Gets the value of the particellaFab property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the particellaFab property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParticellaFab().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParticellaFab }
     * 
     * 
     */
    public List<ParticellaFab> getParticellaFab() {
        if (particellaFab == null) {
            particellaFab = new ArrayList<ParticellaFab>();
        }
        return this.particellaFab;
    }

}
