//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TitoloTerreni"/>
 *         &lt;element ref="{}Riepiloghi"/>
 *         &lt;element ref="{}Particellare"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "titoloTerreni",
    "riepiloghi",
    "particellare"
})
@XmlRootElement(name = "QuadroTerreni")
public class QuadroTerreni {

    @XmlElement(name = "TitoloTerreni", required = true)
    protected String titoloTerreni;
    @XmlElement(name = "Riepiloghi", required = true)
    protected Riepiloghi riepiloghi;
    @XmlElement(name = "Particellare", required = true)
    protected Particellare particellare;

    /**
     * Gets the value of the titoloTerreni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitoloTerreni() {
        return titoloTerreni;
    }

    /**
     * Sets the value of the titoloTerreni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitoloTerreni(String value) {
        this.titoloTerreni = value;
    }

    /**
     * Gets the value of the riepiloghi property.
     * 
     * @return
     *     possible object is
     *     {@link Riepiloghi }
     *     
     */
    public Riepiloghi getRiepiloghi() {
        return riepiloghi;
    }

    /**
     * Sets the value of the riepiloghi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Riepiloghi }
     *     
     */
    public void setRiepiloghi(Riepiloghi value) {
        this.riepiloghi = value;
    }

    /**
     * Gets the value of the particellare property.
     * 
     * @return
     *     possible object is
     *     {@link Particellare }
     *     
     */
    public Particellare getParticellare() {
        return particellare;
    }

    /**
     * Sets the value of the particellare property.
     * 
     * @param value
     *     allowed object is
     *     {@link Particellare }
     *     
     */
    public void setParticellare(Particellare value) {
        this.particellare = value;
    }

}
