//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SezioneAnagrafica"/>
 *         &lt;element ref="{}SezioneTitolare"/>
 *         &lt;element ref="{}SezioneSoggetti"/>
 *         &lt;element ref="{}SezioneAssociazioni"/>
 *         &lt;element ref="{}SezioneConti"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sezioneAnagrafica",
    "sezioneTitolare",
    "sezioneSoggetti",
    "sezioneAssociazioni",
    "sezioneConti"
})
@XmlRootElement(name = "QuadroA")
public class QuadroA {

    @XmlElement(name = "SezioneAnagrafica", required = true)
    protected SezioneAnagrafica sezioneAnagrafica;
    @XmlElement(name = "SezioneTitolare", required = true)
    protected SezioneTitolare sezioneTitolare;
    @XmlElement(name = "SezioneSoggetti", required = true)
    protected SezioneSoggetti sezioneSoggetti;
    @XmlElement(name = "SezioneAssociazioni", required = true)
    protected SezioneAssociazioni sezioneAssociazioni;
    @XmlElement(name = "SezioneConti", required = true)
    protected SezioneConti sezioneConti;

    /**
     * Gets the value of the sezioneAnagrafica property.
     * 
     * @return
     *     possible object is
     *     {@link SezioneAnagrafica }
     *     
     */
    public SezioneAnagrafica getSezioneAnagrafica() {
        return sezioneAnagrafica;
    }

    /**
     * Sets the value of the sezioneAnagrafica property.
     * 
     * @param value
     *     allowed object is
     *     {@link SezioneAnagrafica }
     *     
     */
    public void setSezioneAnagrafica(SezioneAnagrafica value) {
        this.sezioneAnagrafica = value;
    }

    /**
     * Gets the value of the sezioneTitolare property.
     * 
     * @return
     *     possible object is
     *     {@link SezioneTitolare }
     *     
     */
    public SezioneTitolare getSezioneTitolare() {
        return sezioneTitolare;
    }

    /**
     * Sets the value of the sezioneTitolare property.
     * 
     * @param value
     *     allowed object is
     *     {@link SezioneTitolare }
     *     
     */
    public void setSezioneTitolare(SezioneTitolare value) {
        this.sezioneTitolare = value;
    }

    /**
     * Gets the value of the sezioneSoggetti property.
     * 
     * @return
     *     possible object is
     *     {@link SezioneSoggetti }
     *     
     */
    public SezioneSoggetti getSezioneSoggetti() {
        return sezioneSoggetti;
    }

    /**
     * Sets the value of the sezioneSoggetti property.
     * 
     * @param value
     *     allowed object is
     *     {@link SezioneSoggetti }
     *     
     */
    public void setSezioneSoggetti(SezioneSoggetti value) {
        this.sezioneSoggetti = value;
    }

    /**
     * Gets the value of the sezioneAssociazioni property.
     * 
     * @return
     *     possible object is
     *     {@link SezioneAssociazioni }
     *     
     */
    public SezioneAssociazioni getSezioneAssociazioni() {
        return sezioneAssociazioni;
    }

    /**
     * Sets the value of the sezioneAssociazioni property.
     * 
     * @param value
     *     allowed object is
     *     {@link SezioneAssociazioni }
     *     
     */
    public void setSezioneAssociazioni(SezioneAssociazioni value) {
        this.sezioneAssociazioni = value;
    }

    /**
     * Gets the value of the sezioneConti property.
     * 
     * @return
     *     possible object is
     *     {@link SezioneConti }
     *     
     */
    public SezioneConti getSezioneConti() {
        return sezioneConti;
    }

    /**
     * Sets the value of the sezioneConti property.
     * 
     * @param value
     *     allowed object is
     *     {@link SezioneConti }
     *     
     */
    public void setSezioneConti(SezioneConti value) {
        this.sezioneConti = value;
    }

}
