//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SezioneVuota"/>
 *         &lt;element ref="{}Visibility"/>
 *         &lt;element ref="{}TitoloMacchine"/>
 *         &lt;element ref="{}MacchineVar"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sezioneVuota",
    "visibility",
    "titoloMacchine",
    "macchineVar"
})
@XmlRootElement(name = "QuadroVariazioneMotori")
public class QuadroVariazioneMotori {

    @XmlElement(name = "SezioneVuota")
    protected boolean sezioneVuota;
    @XmlElement(name = "Visibility")
    protected boolean visibility;
    @XmlElement(name = "TitoloMacchine", required = true)
    protected String titoloMacchine;
    @XmlElement(name = "MacchineVar", required = true)
    protected MacchineVar macchineVar;

    /**
     * Gets the value of the sezioneVuota property.
     * 
     */
    public boolean isSezioneVuota() {
        return sezioneVuota;
    }

    /**
     * Sets the value of the sezioneVuota property.
     * 
     */
    public void setSezioneVuota(boolean value) {
        this.sezioneVuota = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     */
    public boolean isVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     */
    public void setVisibility(boolean value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the titoloMacchine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitoloMacchine() {
        return titoloMacchine;
    }

    /**
     * Sets the value of the titoloMacchine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitoloMacchine(String value) {
        this.titoloMacchine = value;
    }

    /**
     * Gets the value of the macchineVar property.
     * 
     * @return
     *     possible object is
     *     {@link MacchineVar }
     *     
     */
    public MacchineVar getMacchineVar() {
        return macchineVar;
    }

    /**
     * Sets the value of the macchineVar property.
     * 
     * @param value
     *     allowed object is
     *     {@link MacchineVar }
     *     
     */
    public void setMacchineVar(MacchineVar value) {
        this.macchineVar = value;
    }

}
