//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SezioneVuota"/>
 *         &lt;element ref="{}Visibility"/>
 *         &lt;element ref="{}TitoloManodopera"/>
 *         &lt;element ref="{}FamTempoPieno"/>
 *         &lt;element ref="{}FamTempoParziale"/>
 *         &lt;element ref="{}SalTempoPieno"/>
 *         &lt;element ref="{}SalTempoParziale"/>
 *         &lt;element ref="{}TotTempoPieno"/>
 *         &lt;element ref="{}TotTempoParziale"/>
 *         &lt;element ref="{}Avventizi"/>
 *         &lt;element ref="{}GiornateAnnue"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sezioneVuota",
    "visibility",
    "titoloManodopera",
    "famTempoPieno",
    "famTempoParziale",
    "salTempoPieno",
    "salTempoParziale",
    "totTempoPieno",
    "totTempoParziale",
    "avventizi",
    "giornateAnnue"
})
@XmlRootElement(name = "QuadroManodopera")
public class QuadroManodopera {

    @XmlElement(name = "SezioneVuota")
    protected boolean sezioneVuota;
    @XmlElement(name = "Visibility")
    protected boolean visibility;
    @XmlElement(name = "TitoloManodopera", required = true)
    protected String titoloManodopera;
    @XmlElement(name = "FamTempoPieno", required = true)
    protected String famTempoPieno;
    @XmlElement(name = "FamTempoParziale", required = true)
    protected String famTempoParziale;
    @XmlElement(name = "SalTempoPieno", required = true)
    protected String salTempoPieno;
    @XmlElement(name = "SalTempoParziale", required = true)
    protected String salTempoParziale;
    @XmlElement(name = "TotTempoPieno", required = true)
    protected String totTempoPieno;
    @XmlElement(name = "TotTempoParziale", required = true)
    protected String totTempoParziale;
    @XmlElement(name = "Avventizi", required = true)
    protected String avventizi;
    @XmlElement(name = "GiornateAnnue", required = true)
    protected String giornateAnnue;

    /**
     * Gets the value of the sezioneVuota property.
     * 
     */
    public boolean isSezioneVuota() {
        return sezioneVuota;
    }

    /**
     * Sets the value of the sezioneVuota property.
     * 
     */
    public void setSezioneVuota(boolean value) {
        this.sezioneVuota = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     */
    public boolean isVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     */
    public void setVisibility(boolean value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the titoloManodopera property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitoloManodopera() {
        return titoloManodopera;
    }

    /**
     * Sets the value of the titoloManodopera property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitoloManodopera(String value) {
        this.titoloManodopera = value;
    }

    /**
     * Gets the value of the famTempoPieno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamTempoPieno() {
        return famTempoPieno;
    }

    /**
     * Sets the value of the famTempoPieno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamTempoPieno(String value) {
        this.famTempoPieno = value;
    }

    /**
     * Gets the value of the famTempoParziale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamTempoParziale() {
        return famTempoParziale;
    }

    /**
     * Sets the value of the famTempoParziale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamTempoParziale(String value) {
        this.famTempoParziale = value;
    }

    /**
     * Gets the value of the salTempoPieno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalTempoPieno() {
        return salTempoPieno;
    }

    /**
     * Sets the value of the salTempoPieno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalTempoPieno(String value) {
        this.salTempoPieno = value;
    }

    /**
     * Gets the value of the salTempoParziale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalTempoParziale() {
        return salTempoParziale;
    }

    /**
     * Sets the value of the salTempoParziale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalTempoParziale(String value) {
        this.salTempoParziale = value;
    }

    /**
     * Gets the value of the totTempoPieno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotTempoPieno() {
        return totTempoPieno;
    }

    /**
     * Sets the value of the totTempoPieno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotTempoPieno(String value) {
        this.totTempoPieno = value;
    }

    /**
     * Gets the value of the totTempoParziale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotTempoParziale() {
        return totTempoParziale;
    }

    /**
     * Sets the value of the totTempoParziale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotTempoParziale(String value) {
        this.totTempoParziale = value;
    }

    /**
     * Gets the value of the avventizi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvventizi() {
        return avventizi;
    }

    /**
     * Sets the value of the avventizi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvventizi(String value) {
        this.avventizi = value;
    }

    /**
     * Gets the value of the giornateAnnue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGiornateAnnue() {
        return giornateAnnue;
    }

    /**
     * Sets the value of the giornateAnnue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGiornateAnnue(String value) {
        this.giornateAnnue = value;
    }

}
