//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}nomeRiepilogo"/>
 *         &lt;element ref="{}SezioneVuota"/>
 *         &lt;element ref="{}intestazione1"/>
 *         &lt;element ref="{}intestazione2"/>
 *         &lt;element ref="{}intestazione3"/>
 *         &lt;element ref="{}intestazione4"/>
 *         &lt;element ref="{}righeRiepilogoUv"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nomeRiepilogo",
    "sezioneVuota",
    "intestazione1",
    "intestazione2",
    "intestazione3",
    "intestazione4",
    "righeRiepilogoUv"
})
@XmlRootElement(name = "RiepilogoUv")
public class RiepilogoUv {

    @XmlElement(required = true)
    protected String nomeRiepilogo;
    @XmlElement(name = "SezioneVuota")
    protected boolean sezioneVuota;
    @XmlElement(required = true)
    protected String intestazione1;
    @XmlElement(required = true)
    protected String intestazione2;
    @XmlElement(required = true)
    protected String intestazione3;
    @XmlElement(required = true)
    protected String intestazione4;
    @XmlElement(required = true)
    protected RigheRiepilogoUv righeRiepilogoUv;

    /**
     * Gets the value of the nomeRiepilogo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeRiepilogo() {
        return nomeRiepilogo;
    }

    /**
     * Sets the value of the nomeRiepilogo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeRiepilogo(String value) {
        this.nomeRiepilogo = value;
    }

    /**
     * Gets the value of the sezioneVuota property.
     * 
     */
    public boolean isSezioneVuota() {
        return sezioneVuota;
    }

    /**
     * Sets the value of the sezioneVuota property.
     * 
     */
    public void setSezioneVuota(boolean value) {
        this.sezioneVuota = value;
    }

    /**
     * Gets the value of the intestazione1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntestazione1() {
        return intestazione1;
    }

    /**
     * Sets the value of the intestazione1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntestazione1(String value) {
        this.intestazione1 = value;
    }

    /**
     * Gets the value of the intestazione2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntestazione2() {
        return intestazione2;
    }

    /**
     * Sets the value of the intestazione2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntestazione2(String value) {
        this.intestazione2 = value;
    }

    /**
     * Gets the value of the intestazione3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntestazione3() {
        return intestazione3;
    }

    /**
     * Sets the value of the intestazione3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntestazione3(String value) {
        this.intestazione3 = value;
    }

    /**
     * Gets the value of the intestazione4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntestazione4() {
        return intestazione4;
    }

    /**
     * Sets the value of the intestazione4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntestazione4(String value) {
        this.intestazione4 = value;
    }

    /**
     * Gets the value of the righeRiepilogoUv property.
     * 
     * @return
     *     possible object is
     *     {@link RigheRiepilogoUv }
     *     
     */
    public RigheRiepilogoUv getRigheRiepilogoUv() {
        return righeRiepilogoUv;
    }

    /**
     * Sets the value of the righeRiepilogoUv property.
     * 
     * @param value
     *     allowed object is
     *     {@link RigheRiepilogoUv }
     *     
     */
    public void setRigheRiepilogoUv(RigheRiepilogoUv value) {
        this.righeRiepilogoUv = value;
    }

}
