//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TotSupCatastale"/>
 *         &lt;element ref="{}TotSupUtilizzata"/>
 *         &lt;element ref="{}TotSupSau"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totSupCatastale",
    "totSupUtilizzata",
    "totSupSau"
})
@XmlRootElement(name = "RigaTotali")
public class RigaTotali {

    @XmlElement(name = "TotSupCatastale", required = true)
    protected String totSupCatastale;
    @XmlElement(name = "TotSupUtilizzata", required = true)
    protected String totSupUtilizzata;
    @XmlElement(name = "TotSupSau", required = true)
    protected String totSupSau;

    /**
     * Gets the value of the totSupCatastale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotSupCatastale() {
        return totSupCatastale;
    }

    /**
     * Sets the value of the totSupCatastale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotSupCatastale(String value) {
        this.totSupCatastale = value;
    }

    /**
     * Gets the value of the totSupUtilizzata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotSupUtilizzata() {
        return totSupUtilizzata;
    }

    /**
     * Sets the value of the totSupUtilizzata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotSupUtilizzata(String value) {
        this.totSupUtilizzata = value;
    }

    /**
     * Gets the value of the totSupSau property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotSupSau() {
        return totSupSau;
    }

    /**
     * Sets the value of the totSupSau property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotSupSau(String value) {
        this.totSupSau = value;
    }

}
