//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Categoria"/>
 *         &lt;element ref="{}SottoCategoria"/>
 *         &lt;element ref="{}CapiDetenuti"/>
 *         &lt;element ref="{}CapiPropr"/>
 *         &lt;element ref="{}Cicli"/>
 *         &lt;element ref="{}Durata"/>
 *         &lt;element ref="{}Azoto"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "categoria",
    "sottoCategoria",
    "capiDetenuti",
    "capiPropr",
    "cicli",
    "durata",
    "azoto"
})
@XmlRootElement(name = "RigaCapi")
public class RigaCapi {

    @XmlElement(name = "Categoria", required = true)
    protected String categoria;
    @XmlElement(name = "SottoCategoria", required = true)
    protected String sottoCategoria;
    @XmlElement(name = "CapiDetenuti", required = true)
    protected String capiDetenuti;
    @XmlElement(name = "CapiPropr", required = true)
    protected String capiPropr;
    @XmlElement(name = "Cicli", required = true)
    protected String cicli;
    @XmlElement(name = "Durata", required = true)
    protected String durata;
    @XmlElement(name = "Azoto", required = true)
    protected String azoto;

    /**
     * Gets the value of the categoria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoria() {
        return categoria;
    }

    /**
     * Sets the value of the categoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoria(String value) {
        this.categoria = value;
    }

    /**
     * Gets the value of the sottoCategoria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSottoCategoria() {
        return sottoCategoria;
    }

    /**
     * Sets the value of the sottoCategoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSottoCategoria(String value) {
        this.sottoCategoria = value;
    }

    /**
     * Gets the value of the capiDetenuti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapiDetenuti() {
        return capiDetenuti;
    }

    /**
     * Sets the value of the capiDetenuti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapiDetenuti(String value) {
        this.capiDetenuti = value;
    }

    /**
     * Gets the value of the capiPropr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapiPropr() {
        return capiPropr;
    }

    /**
     * Sets the value of the capiPropr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapiPropr(String value) {
        this.capiPropr = value;
    }

    /**
     * Gets the value of the cicli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCicli() {
        return cicli;
    }

    /**
     * Sets the value of the cicli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCicli(String value) {
        this.cicli = value;
    }

    /**
     * Gets the value of the durata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurata() {
        return durata;
    }

    /**
     * Sets the value of the durata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurata(String value) {
        this.durata = value;
    }

    /**
     * Gets the value of the azoto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAzoto() {
        return azoto;
    }

    /**
     * Sets the value of the azoto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAzoto(String value) {
        this.azoto = value;
    }

}
