//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}valore1"/>
 *         &lt;element ref="{}valore2"/>
 *         &lt;element ref="{}valore3"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "valore1",
    "valore2",
    "valore3"
})
@XmlRootElement(name = "rigaRiepilogo")
public class RigaRiepilogo {

    @XmlElement(required = true)
    protected String valore1;
    @XmlElement(required = true)
    protected String valore2;
    @XmlElement(required = true)
    protected String valore3;

    /**
     * Gets the value of the valore1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValore1() {
        return valore1;
    }

    /**
     * Sets the value of the valore1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValore1(String value) {
        this.valore1 = value;
    }

    /**
     * Gets the value of the valore2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValore2() {
        return valore2;
    }

    /**
     * Sets the value of the valore2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValore2(String value) {
        this.valore2 = value;
    }

    /**
     * Gets the value of the valore3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValore3() {
        return valore3;
    }

    /**
     * Sets the value of the valore3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValore3(String value) {
        this.valore3 = value;
    }

}
