//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 04:07:28 PM CET 
//


package it.csi.smranag.smrgaa.dto.jaxb.fascicolo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Visibility"/>
 *         &lt;element ref="{}TitoloSezSoggetti"/>
 *         &lt;element ref="{}SezioneVuota"/>
 *         &lt;element ref="{}SoggettiCollegati"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "visibility",
    "titoloSezSoggetti",
    "sezioneVuota",
    "soggettiCollegati"
})
@XmlRootElement(name = "SezioneSoggetti")
public class SezioneSoggetti {

    @XmlElement(name = "Visibility")
    protected boolean visibility;
    @XmlElement(name = "TitoloSezSoggetti", required = true)
    protected String titoloSezSoggetti;
    @XmlElement(name = "SezioneVuota")
    protected boolean sezioneVuota;
    @XmlElement(name = "SoggettiCollegati", required = true)
    protected SoggettiCollegati soggettiCollegati;

    /**
     * Gets the value of the visibility property.
     * 
     */
    public boolean isVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     */
    public void setVisibility(boolean value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the titoloSezSoggetti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitoloSezSoggetti() {
        return titoloSezSoggetti;
    }

    /**
     * Sets the value of the titoloSezSoggetti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitoloSezSoggetti(String value) {
        this.titoloSezSoggetti = value;
    }

    /**
     * Gets the value of the sezioneVuota property.
     * 
     */
    public boolean isSezioneVuota() {
        return sezioneVuota;
    }

    /**
     * Sets the value of the sezioneVuota property.
     * 
     */
    public void setSezioneVuota(boolean value) {
        this.sezioneVuota = value;
    }

    /**
     * Gets the value of the soggettiCollegati property.
     * 
     * @return
     *     possible object is
     *     {@link SoggettiCollegati }
     *     
     */
    public SoggettiCollegati getSoggettiCollegati() {
        return soggettiCollegati;
    }

    /**
     * Sets the value of the soggettiCollegati property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoggettiCollegati }
     *     
     */
    public void setSoggettiCollegati(SoggettiCollegati value) {
        this.soggettiCollegati = value;
    }

}
